### ISSUE TITLE
Don't enforce access_token and access_token_secret

### ISSUE THREAD

**Issue by kof** [ttezel/twit#100]
Because in case of app auth

https://dev.twitter.com/docs/auth/application-only-auth

There is no need for this tokens.

If you use tokens, its user auth, so in case of search, different rate limits are applied.

https://dev.twitter.com/docs/api/1.1/get/search/tweets

I suggest to remove required params enforcement completely. Api returns meaningful error messages already.

**Comment by SeanEire** [comment]
Has there been any update on this recently? It would be great if you could use app only authentication with this package.

**Comment by passcod** [comment]
+1

Also see passcod/mtwitter#11 and desmondmorris/node-twitter#81:

> I'm the author of mtwitter, a twitter library that did handle application-only requests. Unfortunately I do not maintain it anymore, but people are still trying to use it... generally I redirect them to this library or to twit, but for application-only requests that doesn't work.
>
> So, advisory: there is demand for this, it does require support in the library itself, and it seems that no updated Node.js twitter library actually supports it. Please consider an implementation, and feel free to rip code out of mine.

**Comment by passcod** [comment]
As a note, the **node-twitter** package implemented support for this in desmondmorris/node-twitter#94.

**Comment by ttezel** [comment]
this was fixed in twit v2.0. Try it out and let me know if you have issues!
