### ISSUE TITLE
Stream for 'site' with follow-argument does nothing

### ISSUE THREAD

**Issue by michaelmcmillan** [ttezel/twit#111]
Hi guys! Great library, it has saved me a lot of work!

I was wondering if you know why this does not work? <code>14515583</code> is the id of my personal Twitter account and <code>13009542</code> is one of my friends. However, when I do a tweet while listening on the stream nothing happens. I expect it to write the text of the tweet to the console (obviously):
```javascript
var stream = twat.stream('site', { follow: ['14515583', '13009542']})
stream.on('tweet', function (tweet) {
  console.log(tweet.text);
});
```

According to the documentation on Twitter it should work.
<img src="http://i.imgur.com/kqFFVSi.png">
**https://dev.twitter.com/docs/api/1.1/get/site**

Thanks!

**Comment by ttezel** [comment]
Hi @michaelmcmillan do you have access to site streams? I'm not able to actually reproduce this since I don't have access to the closed beta. Feel free to reopen with code if you're having this issue still.
