### ISSUE TITLE
blocks/create and blocks/destroy

### ISSUE THREAD

**Issue by rodrigopolo** [ttezel/twit#114]
Calling a blocks/create or blocks/destroy returns erro code 32, I think that endpoint isn't yet implemented.

```
{ [Error: Could not authenticate you]
message: 'Could not authenticate you',
statusCode: 401,
code: 32,
allErrors: [ { message: 'Could not authenticate you', code: 32 } ],
twitterReply: '{"errors":[{"message":"Could not authenticate you","code":32}]}'}
```

**Comment by ttezel** [comment]
This should be invalid at this point, freel free to reopen with code to reproduce it if it's an issue! Thanks :)
