### ISSUE TITLE
Sayfayı yeniledigimde streamingi nasıl durdurabilirim ?

### ISSUE THREAD

**Issue by nicely** [ttezel/twit#115]
Merhaba , stream.on() calısırken sayfayı yeniledigimde arkaplanda streaming devam ediyor bunu nasıl öneleyebilirim , node.js express ve socket.io kullanıyorum kodlarım
app.get('/',callback) içerisinde.

ayrıca .stop() kullanırsam , cannot call method 'abort' of undefined hatası alıyorum

durdurmak için buton kullanıyorum buton u click function ile calıstırıyorum

var stream = T.stream('statuses/filter', {
			track: filtreKelimesi
		})
		
		socket.on('stop', function(data) {
				stream.stop();
				console.log(data)
			}); 

bu durumda socket.on stop geldiginde duruyor ama , durdur a birkez daha basarsam hata veriyor

**Comment by ttezel** [comment]
This shouldn't be an issue anymore! Run `npm update twit` to get the latest version of twit. If it's still an issue, feel free to reopen with the full code to reproduce the issue! Thanks :)
