### ISSUE TITLE
"Could not authenticate you" during friendship/create

### ISSUE THREAD

**Issue by nickboucart** [ttezel/twit#116]
Hi,

I'm using both the streaming and the REST api in my application. Streaming works nice, some to the REST calls too, but for some reason, 
```
twit.post('friendships/create', {
          screen_name: tweet.user.screen_name,
          follow: false
        }, function (err, resp) {
          if (err) {
            return console.log('friendship gave error: ' + JSON.stringify(err));
          }
          console.log('friended');
        });
```
always returns an error:
```
friendship gave error: {"message":"Could not authenticate you","statusCode":401,"code":32,"allErrors":[{"message":"Could not authenticate you","code":32}],"twitterReply":"{\"errors\":[{\"message\":\"Could not authenticate you\",\"code\":32}]}"}
```
I'm pretty sure I am authenticated properly, otherwise the other calls to twitter would'nt work... Any thoughts?

Thanks!
nick.

**Comment by ttezel** [comment]
Hi @rjalili @yasinuslu I added a test for this and boolean encoding seems to work as expected with the snippet below. `npm update twit` to get the latest version. Feel free to reopen if you still have issues! Thanks :)
```
    var twit = new Twit(config1);

    twit.post('friendships/create', {
      screen_name: 'tolga_tezel',
      follow: false
    }, function (err, resp) {
      if (err) {
        return console.log('friendship gave error: ' + JSON.stringify(err));
      }
      console.log('friended');
    });
```

**Comment by rjalili** [comment]
Thanks, @ttezel
Appreciate your code!

**Comment by anuragsingh228** [comment]
I am having same issue. This is my code.
const express = require('express');
const Twitter = require('twit');
const app = express();
const client = new Twitter({
    consumer_key: ' ',
    consumer_secret: ' ',
    access_token: '',
    access_token_secret: ''
});

app.get('/home_timeline', (req, res) => {
    const params = { tweet_mode: 'extended', count: 10 };

    client
        .get(`statuses/home_timeline`, params)
        .then(timeline => {

            res.send(timeline);
        })
        .catch(error => {
            res.send(error);
        });

});
app.listen(3000, () => console.log('Server running'))
