### ISSUE TITLE
Why retrieving individual properties from data retrieved doing T.post("statuses/update"...) doesn't work?

### ISSUE THREAD

**Issue by q2dg** [ttezel/twit#118]
I mean: this code doesn't work and I don't know why!!

var T = new Twit({...})
T.post("statuses/update", { status: "Hello" }, function(err, data) {
	console.log(data.created_at) //DOESN'T WORK
	console.log(data.id)               //DOESN'T WORK
})

"data" isn't in well-formed JSON, so JSON.parse() or JSON.stringify() don't work neither...

**Comment by ttezel** [comment]
I don't think this applies anymore to the later versions of twit. Run `npm update twit` to get the latest version. Thanks!
