### ISSUE TITLE
Public Streaming API `SyntaxError: Unexpected token {`

### ISSUE THREAD

**Issue by maziyarpanahi** [ttezel/twit#119]
Hi

I have few public streaming api up and running for a long time. Lately I see sometimes it crashes the app with this error message:  Error parsing twitter reply: `{"created_at":"Tue Jun 10 22:50:13 +0000 2014","id":476496586496028672,"id_str":"476496586496028672"

I wont put the entire Tweet body here but the error contains the tweet and it ends with this message:  error message `SyntaxError: Unexpected token {`

I am guessing twit accept an event which is not what it expected or starts with '{' instead of '['. 

I am fine with dropping these messages and avoid crashing if it is possible but I think it happens inside twit module before I can do anything with it? right?

Any help would be much appreciated 
Thanks

**Comment by maziyarpanahi** [comment]
It can't be my code as I tested this with just the stream itself being on at 'tweet' and it catches the error on 'error'. It's not always and it happens sometimes as the twitter stream sends something that twit doesn't expect it.

**Comment by lemonzi** [comment]
I also get the same error when Twitter rejects a query for rate limit:

    Error parsing twitter reply: `Exceeded connection limit for user`, error message `SyntaxError: Unexpected token E`

This comes from [lib/parser.js@38](https://github.com/ttezel/twit/blob/master/lib/parser.js#L38), because Twitter sends the error using plain text, not JSON. 

This is a different thing (API mismatch, not Twitter sending malformed JSON), should I open a new issue?

**Comment by talha-asad** [comment]
I also see this message. It comes out randomly, I think this is an issue with twit. The twit stream object returns this in the 'error' callback so its not an error in my code. This is what i get in the log:

```Error parsing twitter reply: `Exceeded connection limit for user`, error message `SyntaxError: Unexpected token E```

**Comment by lemonzi** [comment]
@talha-asad it's the same thing I got. Although twit fails to report it correctly, you are making too many requests to Twitter; limit it to 100 per 15 min (I think), and a single Streaming API connection open.

**Comment by ttezel** [comment]
@lemonzi @talha-asad this is now fixed. `npm update twit` to get the latest version. Thanks :)
