### ISSUE TITLE
user stream on blocked not firing  

### ISSUE THREAD

**Issue by rodrigopolo** [ttezel/twit#121]
The 'user_event' `blocked` and `unblocked` are not working when defined:

```javascript
stream.on('blocked', function (event) {
	console.log(event);
});

stream.on('unblocked', function (event) {
	console.log(event);
});
```

But they are found with diferent names when using the event `unknown_user_event`
`{"event":"block"...`
`{"event":"unblock"...`

BUT also, they are only fired when the authenticated user block or unblocks another user and NOT when the authenticated user gets blocked by someone, I guess it is the way Twitter avoids any controversy between users.

The events should be renamed and the behavior well documented.

**Comment by ttezel** [comment]
Hi @rodrigopolo these events are listened-to now. Run `npm update twit` to get the latest version! Thanks :)
