### ISSUE TITLE
id versus id_str

### ISSUE THREAD

**Issue by jackdbernier** [ttezel/twit#126]
`twit.post('favorites/create', { id: tweet.id_str }, function(err, data, response) {...}`
works just fine.

`twit.post('favorites/create', { id: tweet.id }, function(err, data, response) {...}`
[message=Sorry, that page does not exist, code=34]

This error could be documented and/or casting numerical ids to string.

**Comment by aymericbeaumet** [comment]
When I rely on a library to communicate with an API, I expect the results I get to be pristine. The fact that `tweet.id` must not be used should obviously be documented, however IMHO nothing else needs to be done.

**Comment by helmus** [comment]
Accessing `tweet.id` indicates a programming error, so an exception is in place. That's just my opinion, maybe it's a matter of taste :)

**Comment by aymericbeaumet** [comment]
Well, a one could do as you say and protect with exceptions.

Or look to look at the [potential](https://www.npmjs.com/package/json-bigint) [solutions](https://developer.mozilla.org/en-US/docs/Mozilla/js-ctypes/js-ctypes_reference/UInt64) :)

**Comment by helmus** [comment]
Are you suggesting that twit should include a bigint library to allow tweet id arithmetic's by default ? Or how exactly do you see a bigint lib solving the "don't use tweet.id" problem ?

**Comment by aymericbeaumet** [comment]
Well I do not know if this is a doable solution, neither if the need actually exists. I'm just pointing the fact that JS libraries exist to handle such cases.

But after all, `tweet.id_str` exists and a one would easily be able to build a BigInt from this so... Let's just keep it simple. Maybe your solution is the more appropriate (to throw an exception).

Have you benchmarked the cost of defining a custom getter for so many objects?

**Comment by helmus** [comment]
> Have you benchmarked the cost of defining a custom getter for so many objects?

No I haven't, that might actually be a valid reason to not do it. Perhaps it is just better to document it properly.

**Comment by aymericbeaumet** [comment]
I put up [some tests](http://jsperf.com/definining-custom-getter), and IMHO the performance cost is not worth it. Let's educate :+1:

**Comment by aymericbeaumet** [comment]
Let me know what you guys think: https://github.com/ttezel/twit/wiki/FAQ

/@helmus /@ttezel

**Comment by helmus** [comment]
1. props for the test, I agree that it's best to just leave the twitter response untouched
2. don't link to w3schools
3. If people really want to learn more about IEEE 754 in JS, maybe link in this video: https://www.youtube.com/watch?v=MqHDDtVYJRI 
it does an excellent job at explaining it with great visualizations ( available here: http://bartaz.github.io/ieee754-visualization/ )

**Comment by aymericbeaumet** [comment]
You're right, I removed the W3S link. Those two links of yours are great, feel free to update the FAQ :)

This could totally fit in the readme by now, but I thought we could add more items to this FAQ in the future?

**Comment by deepakmani** [comment]
Hi there,

I'm using tweet.id_str property after doing:
````
client.get('search/tweets', {q: query, count: 100, since_id: since_id}, function(err, data, response) {
                var tweets 		= data.statuses;
  		var num_tweets	= tweets.length;

  		for (var i = 0; i < num_tweets ; i++)
  		{
  			var user_name 			= tweets[i].user.name;
			var text 				= tweets[i].text;
			var user_screen_name 	= tweets[i].user.screen_name; // twitter handle
			var profile_image_url 	= tweets[i].user.profile_image_url; 
			var status_id 			= Number(tweets[i].id_str);
               }
});
````
I'm now getting the wrong status Id, I think it was working a few weeks ago.
All the other properties of the tweet are matching.  Is anyone else seeing this?

Thanks,
Depeak

**Comment by kai-koch** [comment]
@deepakmani 
```JavaScript
// [...]
var status_id  = Number(tweets[i].id_str);
// [...]
```
You are casting a String of an 64-Bit Integer to a Floating-Point Number that can only hold a 53-Bit.
You there by contradict the purpose of id_str in the first place. That is holding a 64-int without loosing precision.
Use:
```JavaScript
// [...]
var status_id  = tweets[i].id_str;
// [...]
```
Do not use ```Number```. If you use tweet.id for something other than being an unique identifier, you need to use a Library that handles Big Numbers.

Every number in Javascript is a Double-Prescision Floating-Point number, this is not accurate for large numbers by default. Why that is read:
http://en.wikipedia.org/wiki/Floating_point#IEEE_754:_floating_point_in_modern_computers

**Comment by deepakmani** [comment]
Thanks! I didn't realize that there was an issue when casting. It seems like there should be a warning somewhere that indicates overflow is happening.

**Comment by ttezel** [comment]
Thanks for discussing this everyone! Love the conversation and @aymericbeaumet thanks so much for putting together the FAQ. I updated the twit readme to link to the FAQ page. Closing this issue.

**Comment by payomdousti** [comment]
just gonna put it out there that this just burned me for a month without realizing it and i have a db full of the wrong ids now...
