### ISSUE TITLE
Always "Twitter Web Client" in "source" field

### ISSUE THREAD

**Issue by EniGMist4** [ttezel/twit#127]
T.get('statuses/user_timeline', { user_id: 'xxxxxxxxx', count: 10 },  function(err, data, response) {
     console.log(util.inspect(data));
});

Gives "<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>" in source field

**Comment by ttezel** [comment]
And are you sure the data returned is coming from a non-"Twitter Web Client" source?

**Comment by ttezel** [comment]
Closing this, `twit` just returns the source that Twitter provides (the data is not modified by twit)
