### ISSUE TITLE
Twit + Socket.io

### ISSUE THREAD

**Issue by nambad** [ttezel/twit#136]
Hi,

I am facing the same issue like https://github.com/ttezel/twit/issues/89 & https://github.com/ttezel/twit/issues/74

Tried a lot of things but nothing seems to work. Can anyone help?

The event listener for on 'tweet' does not fire. Apart from that, when logging the msg from parser.js, it simply returns blanks lines.

Also, the stream does not stop. The disconnect event fires but the stream won't stop

Can someone help please?

The code looks something like this:

https://gist.github.com/nambad/d7e5f1f90935bba87e40

Just keep blank messages from twitter when sending the parameters by socket.io
If the function startstream is called directly, it will work perfectly fine.

**Comment by ttezel** [comment]
If you're still having issues with this please reopen the issue! Run `npm update twit` to try it with the latest version. Thanks!
