### ISSUE TITLE
Extreme cpu/ram usage

### ISSUE THREAD

**Issue by zettam** [ttezel/twit#137]
Whenever I require twit and create a stream, I can see that it consumes a lot of resources on my server (35-50% of 2 cores, and around 100-150 mb ram). This is my fav. twitter api however it exceeds the other twitter apis' resource management by far.

Wanted to ask for opinion, and let the devs know about this.

Cheers

**Comment by ttezel** [comment]
Closing this :) thanks for looking at this guys!
