### ISSUE TITLE
Streaming Error : "Exceeded connection limit for user" when run a program second time

### ISSUE THREAD

**Issue by zStyle** [ttezel/twit#138]
Hi.

After I run a file which contain stream 'statuses/filter'. I could not run it again until next 5-10 minute.
The error is "Exceeded connection limit for user"

This is my code.
```javascript
var Twit = require('twit');

var T = new Twit({
  consumer_key: 'MYTOKEN',
  consumer_secret: 'MYTOKEN',
  access_token: 'MYTOKEN',
  access_token_secret: 'MYTOKEN'
});

//Stream
var stream = T.stream('statuses/filter', {track:'iPhone', language: 'th'});

stream.on('tweet', function (tweet) {
  console.log(tweet);
});

stream.on('error', function (error) {
  console.log(error);
});
```

Thank you

**Comment by euvl** [comment]
getting the same error

**Comment by dsalcedo** [comment]
run a program second time ? Did you mean are you running a second instance in the same project ? If is this the case, you can't do this, only one instance.

**Comment by ttezel** [comment]
Yes as @dsalcedo mentioned Twitter will generally not allow you to form more than one connection to the streaming API at a time with the same set of credentials.

**Comment by ttezel** [comment]
Hi @dsalcedo @euvl @zStyle this is fixed in the later versions of twit! `npm update twit` to get the latest version :) Thanks!
