### ISSUE TITLE
always getting 420 after opening stream three times

### ISSUE THREAD

**Issue by geduldig** [ttezel/twit#139]
I need to close a stream so that when I open a new stream I avoid having multiple streams open.  Any help with a solution would be greatly appreciated.

**Comment by ttezel** [comment]
You can create one stream per set of Twitter API credentials. Twitter doesn't allow you to open more than one stream per set of credentials, and will rate limit you if you keep closing/reopening a stream. There is also rate limiting that Twitter may do on top of this (eg. by IP address).

Based on your comment it seems you only need a single stream - why are you attempting to open a new stream in the first place if you already have one? I don't think I understand what you're trying to do :P

**Comment by ttezel** [comment]
Oh I should mention `twit` manages your stream so it will reopen it automatically if the connection drops or becomes idle. `twit` obeys Twitter's rate limiting so it will manage 420s for you. Just call `.stream()` and consume from the stream, and this is handled for you.

**Comment by ttezel** [comment]
Closing this
