### ISSUE TITLE
Combine the location and the track is not working 

### ISSUE THREAD

**Issue by jayhuang75** [ttezel/twit#140]
I'm try to do a simple application which combine the location and track. But as far as I testing I cant get the right data.

var Location = ['56.7','49.31','-106.34','48.37'];
var stream = T.stream('statuses/filter', { track: ['iPhone 6 Plus','iPhone 6'], language: ['en','fr'], location: Location});

So am I doing the right approach? 

Thx

**Comment by talha-asad** [comment]
btw the op should send lat and lng in number format rather than as string.

**Comment by sputn1k** [comment]
+1 !!!!

**Comment by sputn1k** [comment]
anyone had any luck with this?

**Comment by ttezel** [comment]
See https://github.com/ttezel/twit/issues/57 :)
