### ISSUE TITLE
Code 32 thrown when using ":)" in GET with search/tweets

### ISSUE THREAD

**Issue by JamieKnight** [ttezel/twit#145]
Hiya,

Twitter instructs users to use :) for doing searches filtered by positive tone, and :( for searches filtered by negative tone.

Place :) inside the Q param in twit trigger an auth error (Code 32) from twitter.

Please advise on how i should work around this issue.

Cheers,

Jamie + Lion

**Comment by ttezel** [comment]
Closing this!
