### ISSUE TITLE
Upload image within a tweet

### ISSUE THREAD

**Issue by zettam** [ttezel/twit#149]
Is this possible? Is there a quick workaround?
Thanks.

**Comment by ttezel** [comment]
This is now supported in twit v1.1.20! Check out the README for how to post a tweet with an image (there's an example now).

**Comment by ttezel** [comment]
And to followup with the conversations on this thread, yes POST statuses/update_with_media is deprecated. However, attaching media can be done with POST media/upload, followed by a POST statuses/update referencing that media. See README for the example :)

**Comment by zettam** [comment]
Thank you!
