### ISSUE TITLE
get direct_messages/sent error 403

### ISSUE THREAD

**Issue by juliocesarbr** [ttezel/twit#152]
Well i have this issue and i dont know if get direct_messages/sent works in twit because a i have this error, and i dont find any about this. 

well here is my code

i m trying with this:

setInterval(function() {
  bot.twit.get('direct_messages/sent', { count: 1 }, function(err, reply) {
    if(err) return handleError(err);
    console.log(reply);
  });
}, 4000);

and i have this response: 

response status: 403
data: undefined

i tried with 

bot.twit.get('direct_messages',  function(err, reply) 

and nothing

i have the last version of twit, please if someone have and answer to this

**Comment by SleepyBandit** [comment]
The following works for me on a basic level;
```
T.get('direct_messages/sent', function(err, data, response) {
    console.log(data)
});
```
I don't know how you are declaring your variable for Twit, but if you go with the default T, then the bot.twit part you have is not needed.

**Comment by ttezel** [comment]
The latest version of twit should work fine with all of the REST API calls, try out:
- https://dev.twitter.com/rest/reference/get/direct_messages
- https://dev.twitter.com/rest/reference/get/direct_messages/sent
- https://dev.twitter.com/rest/reference/get/direct_messages/show

etc.

Reopen if you have any issues!

**Comment by DevNitish** [comment]
@ttezel The links provided above is not working. 
I found [this](https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/new-event) on Twitter API documentation. But I am not sure how to get `message_create.target.recipient_id` param for any user.
Can you tell me how I can send a DM to a specific user with Twit api?
