### ISSUE TITLE
403 on group of favorite/create requests, sometimes

### ISSUE THREAD

**Issue by scottherren1** [ttezel/twit#153]
I am getting a 403 on this request, some times. Most times they all error out, but occasionally one or two will succeed. Am I hitting an API limit or something? 

    var params = {
        q: 'marketing'
      , since: datestring()
      , result_type: 'mixed'
      , count: 10
    };
    console.log(params);
    bot.twit.get('search/tweets', params, function(err, data, response) {
      if(err) return handleError(err);

      var tweets = data.statuses;
      tweets.forEach( function (tweet) {
        console.log(tweet);
        var tweet_id = tweet.id_str;
        //var user = tweet.user.screen_name
        //console.log(user)
        //var tweet_body = tweet.text
        
        var favparams = {
          id: tweet_id
        };
        bot.twit.post('favorites/create', favparams, function (err, data, response) {
          if(err) return handleError(err);

          console.log('\nFavorited: ' + tweet_id);
        });
      });
    });

Console output:

    . . .
    response status: 403
    data: undefined

    Favorited: 549425229886652416
    response status: 403
    data: undefined
    . . .

**Comment by aymericbeaumet** [comment]
@scottherren1 As the OP you can close the issue.
