### ISSUE TITLE
Language-filtering and top tweets?

### ISSUE THREAD

**Issue by deemeetree** [ttezel/twit#159]
Hello

I was wondering: does the `search/tweets` have the capacity to only show the top tweets and to filter them by language? Is there any setting that can be added?

Thanks!

**Comment by RakanNimer** [comment]
Yep, to get top tweets and filter by language : 
```javascript
T.get('search/tweets',{q:' movie', 'count': 10, result\_type:'popular', lang:'en'}, function(err, data, response) {});
```

You can also do stuff like : 
```javascript
// Get all the tweets that don't have the word scary in them that have a positive sentiment since 2013-12-27
T.get('search/tweets',{'q':' movie -scary :) since:2013-12-27', 'count': 10, 'result\_type':'popular'}, function(err, data, response) {});

```
Full documentation [here](https://dev.twitter.com/rest/reference/get/search/tweets) and [here](https://dev.twitter.com/rest/public/search)

**Comment by ttezel** [comment]
Closing this :)
