### ISSUE TITLE
Promises suport

### ISSUE THREAD

**Issue by mateuspv** [ttezel/twit#160]
Since promises will be native in ES6 and currently get/post methods do not return to anything important, we could return a Promise using any polyfill.

Opinions?

**Comment by L2G** [comment]
If this happens, just let the author of [blu-twit](https://www.npmjs.com/package/blu-twit) know, as that module would be rendered obsolete.

**Comment by gabrielstuff** [comment]
Yup, should be pretty fast with q ( https://github.com/kriskowal/q )

**Comment by ttezel** [comment]
Hi @gabrielstuff @L2G @mateuspv this has been added in twit v2.2.1. Run `npm update twit` to get it! Thanks :) Here's an example btw:

```js
twit
  .get('account/verify_credentials', { skip_status: true })
  .catch(function (err) {
    console.log('caught error', err.stack)
  })
  .then(function (result) {
    // `result` is an Object with keys "data" and "resp"
    console.log('data', result.data);
  })
```

**Comment by ttezel** [comment]
By the way it still works with callbacks only, with promises only, and with promises and callbacks combined. So use it however you want!
