### ISSUE TITLE
Getting a 404 error

### ISSUE THREAD

**Issue by RazerLiam** [ttezel/twit#161]
I am getting a 404 not found error when I try to retweet or favorite a tweet on stream.
I'm not sure if there is something I'm doing wrong but it works if I try using a static id.
It could just be a delay on the creation of the json file for the tweet. I tried adding a 5 second delay for the favorite and retweet but it did not work.

stream.on('tweet', function (tweet) {
  if (tweet.retweeted == true) {
    return;
  }

  var TweetID = tweet.id;
  
  T.post('statuses/retweet/:id', { id: TweetID }, function (err, data, response) {
    console.log(data);
    if (err) { console.log(err) }
  });
  
  T.post('favorites/create', { id: TweetID }, function (err, data, response) {
    console.log(data);
    if (err) { console.log(err) }
  });

});

**Comment by brunolazzaro** [comment]
I think that it might be because you should be using `tweet.id_str` instead of `tweet.id`. More info here: https://github.com/ttezel/twit/wiki/FAQ

**Comment by RazerLiam** [comment]
Thank you bruno, that works now.
