### ISSUE TITLE
users/lookup API returning error code 34 "Sorry, that page does not exist"

### ISSUE THREAD

**Issue by richsad** [ttezel/twit#163]
I've tried calling users/lookup with both twit.get and twit.post. In both cases I get this error. I've seen this error reported with other libraries in other languages too.

My code:

T.post('users/lookup', { user_id: idList }, function(err, data, response) {
  	if (err) {
  		console.log(err);
  	} else {
  		console.log(data);
  	}
  });

idList is a list of comma delimited user ids. Exact error object is:

{ [Error: Sorry, that page does not exist]
  message: 'Sorry, that page does not exist',
  statusCode: 404,
  twitterReply: '{"errors":[{"message":"Sorry, that page does not exist","code":34}]}

**Comment by vrunoa** [comment]
Hey @richsad I just test this method and it works for me using GET
``` javascript
T.get('users/lookup', { user_id: '783214,6253282' }, function(err, data, response) {
  if(err) {
    console.log(err);
    return;
  }
  console.log(data);
})
```

And if didnt find the user throws a 404 but with an error message: "No user matches for specified terms.'"
```javascript
T.get('users/lookup', { user_id: '0' }, function(err, data, response) {
  if(err) {
    console.log(err);
    return;
  }
  console.log(data);
})
```
```javascript
{ [Error: No user matches for specified terms.]
  message: 'No user matches for specified terms.',
  statusCode: 404,
  twitterReply: '{"errors":[{"code":17,"message":"No user matches for specified terms."}]}',
  code: 17,
  allErrors: [ { code: 17, message: 'No user matches for specified terms.' } ] }
```

**Comment by richsad** [comment]
Yes working for me now too. I wonder if the REST service was down the night I opened this bug.

**Comment by vrunoa** [comment]
:+1:

**Comment by sapkal-manish** [comment]
@vrunoa  How do I get user lookup using screennames? So I can get userid from it. Actually I need userid (twitter accountid) to get tweet. (e.g. tweet api accept only userid)
