### ISSUE TITLE
How to POST media/upload?

### ISSUE THREAD

**Issue by abtx** [ttezel/twit#165]
Does anyone have an example of how to do POST media/upload (https://dev.twitter.com/rest/reference/post/media/upload) and return the uploaded media ID? 
POST statuses/update_with_media is depreciated now :(

Cheers

**Comment by ttezel** [comment]
Hi @abtx! Added support for this to twit last night. I published twit v1.1.20 that supports POST media/upload. I've also added an example to the README to show how to use POST media/upload.

**Comment by abtx** [comment]
@ttezel, this is truly amazing, thanks a lot for the client and for adding the feature. You made my day! Just wondering whether you plan to update the Meteor package as well.  Cheers!
