### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by misterch0c** [ttezel/twit#168]
Hello, I'm trying to use the example code in my app. I just installed it with npm install twit then tried to run the following code:

```
var Twit = require('twit')

var T = new Twit({
    consumer_key:         ''
  , consumer_secret:      ''
  , access_token:         ''
  , access_token_secret:  ''
})

T.get('search/tweets', { q: 'banana since:2011-11-11', count: 100 }, function(err, data, response) {
  console.log(data)
})
```
In the console I get "undefined". I'm 100% sure my consumer key etc are correct

**Comment by ttezel** [comment]
I can't reproduce this behavior - `data` is printed as expected to stdout on my machine. Are you on the latest version of `twit`?

**Comment by misterch0c** [comment]
Turns out I was passing the acces token and secret like this:
access_token: token,
access_token_secret: tokenSecret
token and tokenSecret being the tokens I previously got from the client login (see code here https://gist.github.com/misterch0c/55a9365b838c9668d5c1)
However if I give the value of my token and tokenSecret like this:
access_token: 'ef4zf4mytokenvalue,
access_token_secret: 'efzef44mytokenSecretvalue'
It will work... Why?
