### ISSUE TITLE
POST media/upload for Meteor?

### ISSUE THREAD

**Issue by abtx** [ttezel/twit#170]
Hi, 
I'd be a great help if the Meteor package was updated with Post media/upload. Looking forward! Thanks.

**Comment by gabrielstuff** [comment]
Which Meteor package are you talking about ? Pretty sure ttezel did not create one. Plus now, you can use easily npm module inside meteor without packages.

**Comment by ttezel** [comment]
haha yeah I actually don't use meteor, and haven't ever done anything special to have `twit` work with meteor. Can you just use `npm install` to use npm packages with meteor? If not, which meteor project are you referring to? I can issue a pull request to the maintainer.

**Comment by ttezel** [comment]
Okay it appears you can just use npm packages with npm. Closing this issue - I advise just doing that. Using meteor packages seems like overkill - feel free to reopen if you disagree and we can discuss :)

**Comment by abtx** [comment]
Hi @ttezel , right, seems like someone wrapped up your lib into a meteor package and credited you for it. But it links to your gihub (https://atmospherejs.com/mrt/twit). I'll use npm instead then! thanks a bunch, and again, great little lib.
