### ISSUE TITLE
Media Upload issue

### ISSUE THREAD

**Issue by haydenbleasel** [ttezel/twit#175]
Hey, implementing what should be a relatively simple media upload function from your examples and I'm running into an issue:

```
var b64content = fs.readFileSync(img, { encoding: 'base64' });
twitter.post('media/upload', { media: b64content }, function (err, data, response) {
  console.log(err);
});
```

gives me:

```
{ [Error: Sorry, that page does not exist]
  message: 'Sorry, that page does not exist',
  statusCode: 404,
  twitterReply: '{"errors":[{"message":"Sorry, that page does not exist","code":34}]}',
  code: 34,
  allErrors: [ { message: 'Sorry, that page does not exist', code: 34 } ] }
```

Note: I've checked everything before that console log (the integrity of the image and the base64 string), it's all fine.

**Comment by haydenbleasel** [comment]
Suddenly works now for some reason.

**Comment by codynegri** [comment]
I am having this issue now. Hoping to find a resolution soon.

**Comment by ttezel** [comment]
@codynegri What version of twit are you using?

**Comment by codynegri** [comment]
0.2.0 using  meteor add mrt:twit

**Comment by codynegri** [comment]
Response is:
I20150415-12:45:53.893(-4)? { [Error: Sorry, that page does not exist]
I20150415-12:45:53.893(-4)?   message: 'Sorry, that page does not exist',
I20150415-12:45:53.893(-4)?   statusCode: 404,
I20150415-12:45:53.893(-4)?   code: 34,
I20150415-12:45:53.893(-4)?   allErrors: [ { message: 'Sorry, that page does not exist', code: 34 } ],
I20150415-12:45:53.894(-4)?   twitterReply: '{"errors":[{"message":"Sorry, that page does not exist","code":34}]}' }

**Comment by ttezel** [comment]
@codynegri You're using a very old version of twit that does not implement media upload. Please upgrade to twit v1.1.20 :) I will update the readme now to indicate in the changelog that media upload was added in 1.1.20.

**Comment by codynegri** [comment]
Thanks @ttezel ! That makes sense. I was looking at /lib/twitter.js and seeing the correct URL, so I was utterly confused. Are you aware of a more recent version available on atmospherejs.com?

**Comment by ttezel** [comment]
I have not used atmospherejs.com, but I don't think twit should need to exist on there? Meteor supports installing packages from npm AFAIK. I see that the twit version listed there (https://atmospherejs.com/mrt/twit) is the one you were using - v0.2. Is there some reason that I should ensure the latest version of twit is present there? It seems like overkill if you can just install the latest package via npm.

**Comment by codynegri** [comment]
Yes, that is the one I was using. Using npm presented some errors in my meteor application. When going through the packaging process as I did with atmospherejs, everything worked. I do see where a few others have tried packaging updates (1.0 is the latest), but nothing for the media update. Thanks for the assistance with everything so far.

**Comment by codynegri** [comment]
I got the error working by just using NPM. Thanks for the advise and pointing out I was using an old version. I have tested, and it now works.
