### ISSUE TITLE
Getting all stream events

### ISSUE THREAD

**Issue by zettam** [ttezel/twit#186]
is it possible to get all stream events for user without needing to define "follow" or "tweet" or such?

stream.on("all", function(tw){
//stuff
});

**Comment by ttezel** [comment]
Hi @zettam! Just added this in twit v2.1.0! Try it out and let me know if you have issues :)

**Comment by zettam** [comment]
Thanks this is amazing,
One question though, is it possible to get the whole stream without defining anything (tweet, favorites, an everyth,ng in a single stream) -- I mean, suchs as an event to take "all"

**Comment by ttezel** [comment]
yes, the new `message` event will be emitted whenever an object is received in the stream. This includes tweets, favorites etc. as you are describing

**Comment by zettam** [comment]
Hm, I am having hard time understanding the concept, can you put a tiny example for also future reference?

Thank you

**Comment by zettam** [comment]
ah nevermind I just saw it!

stream.on('message', function (msg) {
  //...
})

**Comment by zettam** [comment]
Thanks! Feel free to close this :)

**Comment by ttezel** [comment]
oh cool, glad you saw it! :+1:
