### ISSUE TITLE
Implement gzip compression in stream

### ISSUE THREAD

**Issue by chafreaky** [ttezel/twit#189]
Hi,

I saw in the lib that the gzip headers are commented with a note to test them. Any plan on implementing them soon? Or any update on what is the hold up, maybe I can help?

Thanks,
Chafik

**Comment by ttezel** [comment]
Hey @chafreaky thanks for asking about that. Yeah I was planning on testing it simply by running unit tests and opening a long-running stream and seeing if I encounter any errors, then just publishing a new version of twit with the change. If you want to help, you could place the gzip option to requests and test the same way, I wouldn't mind some help, especially if you use a different platform eg. linux/Windows. I test on OSX mostly.

**Comment by chafreaky** [comment]
Sadly I test in OSX as well but I'll see what I can do. Thanks for the
update!

**Comment by jasjeev4** [comment]
So once this is implemented we should get gzip support for REST API calls too?

**Comment by ttezel** [comment]
Hi there this is implemented for all API calls now! `npm update twit` to get it! Thanks! :D
