### ISSUE TITLE
Bearer token Error 404

### ISSUE THREAD

**Issue by Volox** [ttezel/twit#190]
Hi,
i cannot obtain a bearer token because the request return a `404 Not Found` error.
I tracked down the exception and is generated in [lib/helpers.js line 114](https://github.com/ttezel/twit/blob/master/lib/helpers.js#L114) because the `body` is set to `undefined`.

Can you plese tell me how to fix this?

**Comment by ttezel** [comment]
This is now handled by returning an Error if this occurs (it should not normally fail). `npm update twit` to get the latest version! Thanks :)
