### ISSUE TITLE
Retry in case of transport-level  error may crash

### ISSUE THREAD

**Issue by super-ienien** [ttezel/twit#195]
I, in the file twitter.js at the line 235 : 
 // retry the request since retries were specified and we got a status code we should retry on
 self.request(method, path, params, callback);

method, path, params and callback are not defined. So if the program execute this line, it will crash.

**Comment by ttezel** [comment]
Hi @super-ienien can you reopen if this still happens for you? This should be fixed in later versions of twit. `npm update twit` to get it. Thanks!
