### ISSUE TITLE
How to use POST while initiating a stream?

### ISSUE THREAD

**Issue by akshayraje** [ttezel/twit#196]
While using twit.stream('statuses/filter') how do I use POST so that I can pass a long string of comma separated userids to follow?

**Comment by ttezel** [comment]
`twit.stream()` is already performing a POST request.

**Comment by ttezel** [comment]
Feel free to reopen if you're having actual issues with it - you should be able to do `twit.stream('statuses/filter', { follow: [ "USERID1", "USERID2", ... ] })`

**Comment by sapkal-manish** [comment]
@ttezel  You have mentioned array of userids. Is it numberic id or can I pass screen name e.g. 'toi' or '@toi'.  
I want tweet by screen name? How Do I get using screen name, because I dont have userid of account which I want to streaming...
