### ISSUE TITLE
Calling stream.stop() produces an error

### ISSUE THREAD

**Issue by Precel** [ttezel/twit#197]
I'm using Meteor and mrt:twit 0.2.0 from atmosphere. What I'm trying to achieve is to change 'track' parameter of stream at runtime. As far as I know I can't run two streams at once, so I update stream parameter and call start() and stop(). Is that correct way? Unfortunately, stop() produces an error:
 >Exception while invoking method 'newSearch' TypeError: Cannot call method 'abort' of undefined 
>at OARequest.stop (/Users/rafal/.meteor/packages/mrt_twit/.0.2.0.1ci6a8t++os+web.browser+web.cordova/npm/node_modules/twit/lib/oarequest.js:109:16

Details: https://ui.kadira.io/et/8c487ab9-0072-4e53-8616-8d3ca07b8045

My code:
```javascript
function UpdateStream() {
    if(isStreamStarted) {
        stream.stop();
    }

    stream = T.stream('statuses/filter', {
        track: tracks
    });

    if(isStreamStarted) {
        stream.start();
    }
    else StartStream();

    console.log("Stream updated! Followed tracks: "+ tracks);
}

function StartStream() {
    isStreamStarted = true;
    stream.on('tweet', Meteor.bindEnvironment(function (tweet) {
        Messages.insert({
            text: tweet.text,
            picture: tweet.user.profile_image_url,
            created_at: tweet.created_at,
            tweet_id: tweet.id,
            author_id: tweet.user.screen_name,
            author: tweet.user.name
        });
    }));
```

**Comment by ttezel** [comment]
hi @Precel can you try upgrading to the latest version of twit? The flow you're describing (calling stop, updating the parameters, then calling stream again) should work fine.

**Comment by ttezel** [comment]
This specific issue I've seen before and should be fixed in a later version of twit than what you're using. I encourage upgrading to latest version. To do so, you probably need to `npm install` it rather than using the meteor package.

**Comment by ttezel** [comment]
Closing this, please reopen if you have issues with the latest version of twit.

**Comment by tkntobfrk** [comment]
This post was super helpful, I was stuck on this for a few days. I validated this works in the latest version of twit. Maybe I'll push to github when I have a chance.

//twitter.js
var Twit = require('twit');
var req = require('request');
var io = require('../app').io;
var SOCKETIO_CONFIG_EVENT = 'tweet-io:config';
var stream = {};
var isStreamStarted = false;
T = new Twit({

	consumer_key: 'xxx',
	consumer_secret: 'yyy',
	access_token: 'zzz',
	access_token_secret: 'zzz'

});
var configClient = function() {
//	stream = T.stream('statuses/filter', { track: [search], language: 'en' });
	console.log('Update Track');

	if(isStreamStarted) {
		stream.stop();
	}

	var rand = random(1,10);
    console.log(rand);
	if(rand <= 5) {
		stream = T.stream('statuses/filter', {track: ['Test'], language: 'en'});
	}
	else {
		stream = T.stream('statuses/filter', { track: ['bananas', 'oranges', 'strawberries'] })
	}
//	stream.start();
	if(isStreamStarted) {
		stream.start();
	}
//	else

		StartStream();

	console.log("Stream updated! Followed tracks: ");
};
function random (low, high) {
	return Math.random() * (high - low) + low;
}
io.sockets.on('connection', function(socket) {

	socket.on(SOCKETIO_CONFIG_EVENT, configClient);

});

function StartStream() {
	isStreamStarted = true;
	console.log('stream configured');
	stream.on('connect', function (request) {
		console.log('Connected to Twitter API');
	});

	stream.on('disconnect', function (message) {
		console.log('Disconnected from Twitter API. Message: ' + message);
	});

	stream.on('reconnect', function (request, response, connectInterval) {
		console.log('Trying to reconnect to Twitter API in ' + connectInterval + ' ms');
	});

	stream.on('tweet', function (tweet) {
		console.log(JSON.stringify(tweet));
	});
}

//app.js
var express = require('express');
var app = express();
var server = app.listen(3000);
var io = require('socket.io').listen(server);
exports.io = io;

console.log('started on port ' + server.address().port);

//Configuration
app.use(express.json());
app.use(express.urlencoded());
app.use(express.logger());

app.all('*', function(req, res, next) {
  	res.set('Access-Control-Allow-Origin', '*');
  	res.set('Access-Control-Allow-Methods', 'GET, POST, DELETE, PUT');
  	res.set('Access-Control-Allow-Headers', 'X-Requested-With, Content-Type');
  	if ('OPTIONS' == req.method) return res.send(200);
  	next();
});

var twitter = require('./config/twitter');

//index.js
some front end function to send SOCKETIO_CONFIG_EVENT
