### ISSUE TITLE
Upgrade to 2.1.0 error in streaming lib - self.request.on('response', function (response) {

### ISSUE THREAD

**Issue by tkntobfrk** [ttezel/twit#199]
I was using 1.1.14 and found that I couldn't change the filter parameter on streaming so decided I'd try to upgrade to the newest version. I'm getting the error below. Any ideas?

...\api\node_modules\twit\lib\streaming-api-connection.js:70
  self.request.on('response', function (response) {
              ^
TypeError: Cannot read property 'on' of undefined
    at StreamingAPIConnection._startPersistentConnection (...\api\node_modules\twit\lib\streaming-api-connection.js:70:15)
    at StreamingAPIConnection.start (...\api\node_modules\twit\lib\streaming-api-connection.js:165:8)
    at ..\api\node_modules\twit\lib\twitter.js:274:27
    at process._tickDomainCallback (node.js:381:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by tkntobfrk** [comment]
issue was calling stream.stop(); within a checking routine at startup

**Comment by ttezel** [comment]
I'm re-opening this issue since calling `stream.stop()` before the stream was started shouldn't raise such a cryptic error.

**Comment by ttezel** [comment]
@tkntobfrk I can't reproduce this, can you post code that causes this to occur?

**Comment by tkntobfrk** [comment]
I didn't checkin a local version that produced this error, but I think this will generate the same error. This isn't exactly what I was doing but should produce the same error I think.

stream.on('connect', function(request) {
	console.log('Connected to Twitter API');
	stream.stop();
});

**Comment by ttezel** [comment]
Hi @tkntobfrk this shouldn't be an issue anymore I think - I wrote a test that verifies that stop() works in all states: https://github.com/ttezel/twit/blob/master/tests/streaming.js#L615
