### ISSUE TITLE
TLSSocket Error

### ISSUE THREAD

**Issue by ayhankuru** [ttezel/twit#201]
socket fails, error this.

```
tls.js:182
      var commonNames = cert.subject.CN;
                                    ^

TypeError: Cannot read property 'CN' of undefined
    at Object.checkServerIdentity (tls.js:182:37)
    at TLSSocket.<anonymous> (_tls_wrap.js:1016:29)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._finishInit (_tls_wrap.js:566:8)

```

[tls: handle empty cert in checkServerIndentity #2343](https://github.com/nodejs/node/pull/2343)

**Comment by ayhankuru** [comment]
Bu arada nodejs'nin eski sürümlerinde hata mevcutmu bilmiyorum, ben iojs 3.0.0 kullanıyorum ve stream bağlantısı belli bir süre sonra bu hatayı verip sonlanıyor.Modulde hata olmayabilir iojs pull request'inide referans olarak verdim

**Comment by alantva** [comment]
Same problem here. Any progress?

![node_erro](https://cloud.githubusercontent.com/assets/13892426/9410761/605446c4-47f8-11e5-863d-ca22218e719b.png)

![node_process](https://cloud.githubusercontent.com/assets/13892426/9410773/68e91ecc-47f8-11e5-801e-566148e69b4c.png)

**Comment by ayhankuru** [comment]
@alantva merged the pull request, still wait iojs and nodejs new version :(

**Comment by alantva** [comment]
@ayhankuru then it is a problem with node and the iojs? some way to work around this?

**Comment by ayhankuru** [comment]
@alantva  yes this problem iojs and nodejs

**Comment by alantva** [comment]
@ayhankuru ok, thank u

**Comment by Pandazaur** [comment]
Does this problem persist on the io.js version 3.3.0 ?

**Comment by ayhankuru** [comment]
I am using iojs  v3.2.0 and not problems ?

**Comment by ayhankuru** [comment]
[3.2.0 CHANGELOG ](https://github.com/nodejs/node/blob/master/CHANGELOG.md#2015-08-25-version-320-rvagg)

[d9b70f9cbf] - tls: handle empty cert in checkServerIndentity (Mike Atkins) #2343

**Comment by Pandazaur** [comment]
Thank you !

**Comment by ttezel** [comment]
Closing this, reopen if you're still having isues!
