### ISSUE TITLE
Oauth 1 Flow

### ISSUE THREAD

**Issue by deepakmani** [ttezel/twit#203]
Hi Tolga,

This might be more of a question than an issue. I see that there is a helper function to run Oauth 2.0 flow for app authentication. I am unable to find an Oauth 1.1 flow for user authentication. Is there something I am missing.

Thanks,
Deepak

**Comment by ttezel** [comment]
When you construct a twit instance like:

```js
var twit = new Twit({
  consumer_key:         '...',
  consumer_secret:      '...',
  access_token:         '...',
  access_token_secret:  '...',
})
```
Any calls you make like `twit.post()` etc are using OAuth1.0 to sign your requests. Feel free to reopen if this doesn't make sense!
