### ISSUE TITLE
{ code: 89, message: 'Invalid or expired token.' } 

### ISSUE THREAD

**Issue by gauravgaria** [ttezel/twit#204]
Not able to get the response please help asap
getting this error message:- message: 'Invalid or expired token.' 

code:-

                         var tweet = new Twit({
    consumer_key:         tw_cKey, 
    consumer_secret:      tw_cKeySecret,
     access_token:         tw_token, 
     access_token_secret:  tw_tokenSecret
});

                      tweet.get('search/tweets', function(err, data, response) {
  console.log(data)
  res.json(data);
});

**Comment by tkntobfrk** [comment]
I think this just means your  access_token, access_token_secret are not valid. Are you getting/updating them correctly.  You could always just run as the app only auth if you are testing stuff.

{
    consumer_key:         '...'
  , consumer_secret:      '...'
  , app_only_auth:        true
}

**Comment by iamstarkov** [comment]
you need to [get twitter api tokens](https://iamstarkov.com/get-twitter-tokens/)

**Comment by ttezel** [comment]
Feel free to reopen if your credentials are valid and you're still having issues! `npm update twit` to get the latest version. Thanks :)

**Comment by onojatreasure** [comment]
Manage your app on twitter and make sure your api keys and tokens are complete (4). Also, check permission of your app, make sure its "Read, Write and Direct Message"

**Comment by vasubits** [comment]
I am getting the same error, I tried @onojatreasure  solution..but it is not working...

**Comment by thomasfaller** [comment]
Getting the same error here on my Twitter Bot:
https://github.com/thomasfaller/NodeJS-Twitter-bot/blob/master/app.js

I regenerated new tokens and made sure the permissions included 'direct messages' (it doesn't by default, but I still get the error.

Any thoughts?

**Comment by thomasfaller** [comment]
Hmmm found that comment in the Twitter docs:

`Changes to the application permission model will only reflect in access tokens obtained after the permission model change is saved. You will need to re-negotiate existing access tokens to alter the permission level associated with each of your application's users.`

So if you change permissions and save, you will need to regenerate new token keys.

**Comment by vasubits** [comment]
Include (- ) in access token .

Regards,
Vasundhara.

**Comment by filipcoja** [comment]
My Access Token is always Invalid or expired after defollowing one person with my bot, any ideas why?

**Comment by Samreay** [comment]
@filipppp - same issue for me. After unfollowing some users, the token becomes invalid or expired, and I have no idea why. Did you ever figure it out?

**Comment by dheeman00** [comment]
Please check if you have properly placed the credentials.

**Comment by Fedy-Belaid** [comment]
It's all about correctly placing your credentials, keep in mind that changing permissions requires updating creds in your code!

**Comment by lunaperegrina** [comment]
I'm using twitter api v2 and the error {errors: [{message: 'Invalid or expired token', code: 89}]} keeps happening. I tested it with cURL and it worked fine. I have no idea what to do. I've regenerated the tokens, and it still doesn't work.

![image](https://user-images.githubusercontent.com/57403682/142797080-ffabd2cc-e7c3-4411-b36b-574226ac9cee.png)

**Comment by roe-men** [comment]
i get the same errors, has anybody figured this out?

**Comment by JukedByLife** [comment]
If you only need to access account activity from twitter you can use the bearer token for app credentials.

https://dev.to/twitterdev/a-comprehensive-guide-for-using-the-twitter-api-v2-using-tweepy-in-python-15d9
https://developer.twitter.com/en/docs/authentication/oauth-2-0/bearer-tokens

```# Function to extract tweets
def get_tweets(username):
    # Authorization
    client = tweepy.Client(bearer_token=os.getenv('BEARER_TOKEN'))

    query = 'from:{}'.format(username)
    tweets = client.search_recent_tweets(query=query, tweet_fields=['context_annotations', 'created_at'], max_results=10)

    temp = []

    for tweet in tweets.data:
        temp.append(tweet.text)

    return temp
