### ISSUE TITLE
handleDisconnect() not implemented?

### ISSUE THREAD

**Issue by mfn** [ttezel/twit#207]
I just relaying this from reading the sources, I did not actually encounter this.

When looking at https://github.com/ttezel/twit/blob/951fb96488308093a7a701f46212b4c0241642a4/lib/streaming-api-connection.js#L266 : 
```
    else if (msg.disconnect)      { self.handleDisconnect(msg) }
```
But it doesn't seem a `handleDisconnect` implementation exists anywhere?

I.e. https://github.com/ttezel/twit/search?utf8=%E2%9C%93&q=handleDisconnect only turns ob this one occurrence?

Sorry if this is a non-issue and there's some other magic involved making this work ... I just don't spot anything obvious too me.

**Comment by super-ienien** [comment]
:+1:

**Comment by ttezel** [comment]
This has been fixed in later commits :)
