### ISSUE TITLE
openssl related issue.

### ISSUE THREAD

**Issue by m4mum** [ttezel/twit#209]
Hi

suddenly since last few days, previously working script is showing below error

EVP_PKEY_get1_RSA:expecting an rsa key:../deps/openssl/openssl/crypto/evp/p_lib.c:288:

I don't know this is related or no, but any help?  My node script which is using twit was working fine earlier. I tried restarting but no luck.

**Comment by ttezel** [comment]
Can you show code reproducing this? Reopen if it's still happening and you an reproduce! Thanks :)
