### ISSUE TITLE
Twitter Stream disruption - Error handling for socket hang ups!

### ISSUE THREAD

**Issue by KingScooty** [ttezel/twit#213]
So the Twitter Streaming API is having issues at the moment:

![Issues](https://s3.amazonaws.com/f.cl.ly/items/2w2b3n421M41383S3F24/Screen%20Shot%202015-10-16%20at%2023.25.29.png)

This is having a severe effect on Twit, and takes down the node process every time there's a socket hang up. Here is the error that isn't currently being caught:

```bash
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at createHangUpError (_http_client.js:203:15)
    at TLSSocket.socketCloseListener (_http_client.js:235:23)
    at emitOne (events.js:82:20)
    at TLSSocket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)
```

**Comment by KingScooty** [comment]
Closed this issue as i thought it may have been something else causing it, but i'm getting the same errors all of a sudden with another project that also uses Twit.

The Twitter Stream issues definitely seem to be causing this error.

**Comment by ttezel** [comment]
Can you confirm that attaching an error handler doesn't fix things?
eg.
```js
var stream = T.stream('statuses/sample');

stream.on('error', function (err) {
  console.log('error', err);
})
```

**Comment by ttezel** [comment]
This should be fixed now by the way, Twit now handles stalls in the stream gracefully. `npm update twit` to get the latest version! Thanks :)
