### ISSUE TITLE
How to exclude retweets

### ISSUE THREAD

**Issue by Divyanshu07** [ttezel/twit#223]
How do i ignore re-tweets from search api. (T.get())?

**Comment by dsalcedo** [comment]
Concatenating "-filter:retweets" to the end of your query string works best.

If you simply add -RT you might run into issues with accidentally filtering tweets containing "RT" for example "Russia Today" will use that string quite a lot!

The following pages describe Twitter search operators:

https://support.twitter.com/articles/71577-using-advanced-search
http://thesocialchic.com/2013/04/26/how-to-master-twitter-search/

**Comment by ttezel** [comment]
Thanks @dsalcedo! closing this :)
