### ISSUE TITLE
Documentation (README.MD) - since: field date format

### ISSUE THREAD

**Issue by the-bobo** [ttezel/twit#224]
The example banana query gives us: `since: 2011-11-11` and tells us this will search for tweets with `banana` since November 11, 2011.

Is the formatting for `since` `YYYY-MM-DD` or `YYYY-DD-MM`? Unfortunately this example is ambiguous.

Thanks!

**Comment by the-bobo** [comment]
Okay, found a response on https://dev.twitter.com/rest/public/search - `superhero since:2015-07-19` - the field is YYYY-MM-DD.

Submitting a pull request to edit the documentation on README.MD with a more helpful date example.

Thanks!

**Comment by ttezel** [comment]
This has been clarified in the readme. Sorry for the ambiguity!
