### ISSUE TITLE
State of maintenance of project

### ISSUE THREAD

**Issue by gabrielstuff** [ttezel/twit#226]
Hi @ttezel,

Could you give us more hints about pull request integration ? code review ? and issues attribution and solving / closing ?

There are more than 20 pull request and some are very old: 2013.
There are also 65 issues and some are already fixed or not really issues.

Would you mind some help for maintening the project ? 
Maybe create it's own organization.

There are tons of twitter module that all do many things. But this one is really great : 
:star: 1587, :fork_and_knife:  211 , and 81 people watching. 

It would be really nice to see it evolve and take into account the community.

Thanks !

**Comment by the-bobo** [comment]
great idea, would love to hear your thoughts @ttezel, and thanks for bringing it up @gabrielstuff :)

**Comment by gabrielstuff** [comment]
Hello,

As it as now been 18 days, I'd really would like to know what other contributors think about this ? 
Maybe I'm wrong but I really feel the project need more maintenance.

Thanks !

**Comment by mkody** [comment]
>@mkody what do you think about an Organization for twit ?
Well, if you wan't to name it `twit`, shouldn't we get @ttezel permission, since this would mean the Organization would be (like) the "new official" home of the project?

But GitHub is great about something: forks. `twit` could be forked on a new name and be updated with merging PRs and closing some tickets on the new fork.

**Comment by gabrielstuff** [comment]
yes we can name it whatever needed / liked. I just suggest that because, it seams like people want to share and learn with the twitter API. 
This looks useful to have multiple maintainer and people able to accept pull request and review code.

**Comment by talha-asad** [comment]
I would be willing to maintain this project, if the author agrees ofcourse.

**Comment by gabrielstuff** [comment]
@ttezel wondered if you were interested in giving us your two cents ? Thanks a lot

**Comment by ttezel** [comment]
Hi guys, sorry for the delay. I've been quite busy with other projects. This week I fixed up many of the issues and feature requests. We are currently at 3 issues and 2 pull requests left, and I plan to continue addressing them.

**Comment by ttezel** [comment]
As a follow-up to this issue I will create a section in the readme.md specifying guidelines on how to contribute to the project.

**Comment by talha-asad** [comment]
@ttezel Thanks for putting in all this work. I still think you should add someone else on this project, in case you are busy, the project will still be well maintained.

**Comment by gabrielstuff** [comment]
Awesome! Best news of the week-end among new pictures from NASA.
