### ISSUE TITLE
Not an issue per se, but can I update the params on an existing stream?

### ISSUE THREAD

**Issue by scottbert** [ttezel/twit#232]
Hi,

I used to be able to do:
```javascript
stream = twitter.stream(‘statuses/filter’, streamingOptions);
```
and then
```javascript
runner = setInterval(() => {
        stream.params.track = query();
    }, 30000);
```
Would update the search terms every 30 seconds. This worked fine in V1.x, do you know if there’s a nice way to do this in V2.x? stream.params doesn’t exist and I can’t see anything obvious on the object.

Thanks in advance!

**Comment by ttezel** [comment]
Hi @scottbert you must stop the stream and create a new one with new params - this is because the params are used to construct a new HTTP request to Twitter to start the streaming.
