### ISSUE TITLE
how to get the tweets of a specific user using the streaming service

### ISSUE THREAD

**Issue by abbood** [ttezel/twit#233]
testing this worked like a charm:

```
// 
//  filter the twitter public stream by the word 'mango'. 
// 
var stream = T.stream('statuses/filter', { track: 'mango' })
 
stream.on('tweet', function (tweet) {
  console.log(tweet)
})
```

I tried, however, to test capturing the tweets of a specific user (in this case.. me), so I simply used the [curl generator](https://dev.twitter.com/oauth/tools/signature-generator/9456474?nid=800) of the twitter api:

```
curl --get 'https://api.twitter.com/1.1/users/show.json' --data 'screen_name=abbood' --header 'Authorization: OAuth oauth_consumer_key="***", oauth_nonce="***", oauth_signature="***", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1453990017", oauth_token="***", oauth_version="1.0"' --verbose
```

and got this:
```
{"id":16298157,"id_str":"16298157","name":"abbood","screen_name":"abbood"...
```

so then i plugged that data back like so:
```
var userId = '16298157';
var stream = T.stream('statuses/filter', { follow: userId });
stream.on('tweet', function (tweet) {
    console.log("on tweet");
});
```

i ran the code using node.. then i tested tweeting a dummy tweet.. but nothing was returned! What am I doing wrong?

**Comment by ttezel** [comment]
This is likely an issue with you posting the tweet, then starting to stream, and missing the tweet. If you start your stream, then post the tweet while your stream is running, I think you'll get the event.

**Comment by sapkal-manish** [comment]
How Do I get tweet using screen_name? I need as follows, Is it possible or how to do it?
var screen_name = 'abbood';
var stream = T.stream('statuses/filter', { follow: screen_name });
stream.on('tweet', function (tweet) {
    console.log("on tweet");
});
