### ISSUE TITLE
Cannot load https://userstream.twitter.com/1.1/user.json. Response for preflight has invalid HTTP status code 400

### ISSUE THREAD

**Issue by johnRivs** [ttezel/twit#234]
I'm using Chrome. Installed the package via npm and used browserify.

I've followed the instructions and I always get `cannot load https://userstream.twitter.com/1.1/user.json. Response for preflight has invalid HTTP status code 400` 

In fact, I've tried other packages and I get the same error. I can use curl from the command line to consume this endpoint, the one Twitter gives me from their OAuth signature generator. 

Also, right before that message, it shows `OPTIONS https://userstream.twitter.com/1.1/user.json`

Is it because I'm testing locally?

**Comment by blister** [comment]
400 is the response for bad request. I briefly poked around and received a 401 Unauthorized and a 405 Not Allowed but didn't do anything to make sure I had the proper credentials. What request parameters are being sent along? What authentication scheme are you using? OAuth?

**Comment by johnRivs** [comment]
It happens wether I send allowed parameters or not. Using OAuth.

**Comment by ttezel** [comment]
Hi @johnRivs @blister I don't think you will be able to use the Twitter REST or Streaming APIs at all from chrome (or most web browsers). The reason why is that they will send that OPTIONS request to Twitter (which I don't think you can block) so you'll have to make the request from a server or some other enviroment that is not within the browser. You can for example make an AJAX route on your web server that then makes use of the REST or Streaming API's to make requests on the browser's behalf.
