### ISSUE TITLE
Twitter Stream reconnects after being stopped

### ISSUE THREAD

**Issue by jijo1994** [ttezel/twit#236]
I open a stream tracking a given keyword and then after some period of time the stream seems to reconnect. I am pretty sure that is caused by some changes made in the commits from a day ago as it was working fine yesterday.

**Comment by jijo1994** [comment]
I open a stream tracking a given keyword and then after some period of time the stream seems to reconnect. I am pretty sure that is caused by some changes made in the commits from a day ago as it was working fine yesterday.

**Comment by ttezel** [comment]
@jijo1994 what issue are you having specifically? If Twit loses network connectivity or the stream stalls (or Twitter rate limits you) it is possible to stop streaming and Twit will automatically reconnect for you to continue streaming in these scenarios. Therefore reconnecting is not neccessarily abnormal. I have tested stopping/restarting the stream, and leaving it running, getting rate limited and reconnecting automatically and these operations seem to be functioning correctly on the latest version of twit.

**Comment by jijo1994** [comment]
I am stopping the stream intentially after a particular number of tweets are received, then after some timeout the stream seems to be reconnecting automatically. I don't want this behaviour since I have closed/stopped the stream and it's not due to connectivity or rate limit issues.

**Comment by ttezel** [comment]
Twit should not be reconnecting automatically if you call `.stop()` on the stream. Can you show code that reproduces this issue?

**Comment by jijo1994** [comment]
The code is nothing special, it was taken from the api documentation.

var stream = client.stream('statuses/filter', {track: 'javascript', locations: '-180,-90,180,90'});
...
socket.on('close', function () {
 		logger.info('closed');
 });

Anyway, the problem seems to dissapeared but from time to time I am getting the following error" Error- Gzip error: incorrect header check. What might be causing this?

**Comment by ttezel** [comment]
@jijo1994 can you try installing the latest version of twit and see if you're still getting the gzip error? `npm update twit` to get it.

**Comment by ttezel** [comment]
@jijo1994 closing this - that gzip error should be fixed in the latest version of twit. Feel free to reopen if you get errors with the latest version of twit! Thanks :)
