### ISSUE TITLE
user ids now exceed JS number support, provide api for returning ids as strings? 

### ISSUE THREAD

**Issue by sideburnie** [ttezel/twit#239]
if you create a new twitter account you may get a userid that exceeds JS's 58 bits of number (floating point) resolution (and it will just truncate to 58 bits)... a simple solution might be to provide another version of the api that returns an array of strings? 

repro: 
create a new twitter account
with newly created account, follow the account you have twitt authenticated against
log the id of the new account
do reverse lookup of the id, find it doesn't match, find that JS has truncated the ID

**Comment by sideburnie** [comment]
somewhat easier: you could just pass the full response body through and let the client deal with it. it looks like https://github.com/desmondmorris/node-twitter does this?

**Comment by ttezel** [comment]
@sideburnie I think twitter returns `id_str` whenever it returns `id` in an HTTP response. As long as you use `id_str` instead of `id` everywhere I don't think you should have issues.

**Comment by ttezel** [comment]
Closing this. If you have issues with `id_str` feel free to reopen!

**Comment by sideburnie** [comment]
ah, thanks!

**Comment by ttezel** [comment]
@sideburnie np! :)
