### ISSUE TITLE
Unfollow event does not fire.

### ISSUE THREAD

**Issue by lmenus** [ttezel/twit#243]
Hi,

I am trying to implement Twit as follows:

`const user     = twitter.stream('user', { stringify_friend_ids: true, with: 'user' });`

And I tried to listen for the 'follow' and 'unfollow' events as listed in the documentation. However, I noticed that the unfollow event would not fire, so I replaced the listener with the generic one as you show in the example:

`stream.on('user_event', function (eventMsg) {
  //...
})`

But this still does not fire the unfollow event. Follow works as expected. Any suggestions on what I might be doing wrong?

Thanks,

Lubos

**Comment by luisfavila** [comment]
From what I understood, the unfollow will trigger only if you are the one unfollowing. If someone is unfollowing you, it won't trigger at all. I don't think it's a bug but a twitter limitation instead.

**Comment by rert** [comment]
It is true, like @luisfavila said, It's twitter API limitation, I'll fire on you unfollowing someone, not if someone has unfollowed you .

**Comment by camilleeyries** [comment]
Someone can close this issue ?
