### ISSUE TITLE
Twit does not handle disconnect code 6 properly when streaming

### ISSUE THREAD

**Issue by CTassisF** [ttezel/twit#252]
Hello.

Looks like Node.js hangs when streaming is running and the tokens of that streaming are revoked.
Example:
```
{ disconnect: 
   { code: 6,
     stream_name: 'xxxxxxxxxx',
     reason: 'token revoked for userId xxxxxxxxxx' } }
events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:363:17)
```
Can you please fix this issue?

Thanks in advance.

**Comment by ttezel** [comment]
It looks like your token has been revoked. There isn't anything Twit can do to fix this; you can use the `GET account/verify_credentials` call to check if your credentials are still valid at any time. I think you'll have to get a new set of credentials for the user you're authenticating as.

**Comment by CTassisF** [comment]
I know there isn't much to do when credentials are revoked, but the problem I am trying to report is that the Node.js process **crashes** when a user revokes credentials for a streaming that is currently running.

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:363:17)
```
^ This is the error when the process crashes because of a streaming being abruptly interrupted.

Is it possible for Twit to handle this error gracefully?

Thanks in advance.

**Comment by ttezel** [comment]
Yes - as the error is mentioning, you must listen for the `error` event.

**Comment by ttezel** [comment]
ie. you can handle it by doing something like:

``
stream.on('error', function (err) {
  // handle the error here
})
``
