### ISSUE TITLE
need more then 100 tweet result

### ISSUE THREAD

**Issue by isoftmaster** [ttezel/twit#262]
i tried tweet search but according to twitter api count limit is 100 per page 

```
T.get('search/tweets', { q: 'username', count: 500 }, function(err, data, response) {
  var tweets= data.statuses;
  console.log(tweets.length)
})
```
output 
100

is there any way to can count total tweet by a username with a hash in specific day 
eg: 
**#ThingsiJustLove from:@xyz_user on 26-apr-2016**
i want total number of tweets posted by this user with this hashtag in specific date

if anyone have any idea please share

**Comment by thegreatmichael** [comment]
in the response, your get back a next_results property. if this property exists in the data you get back, and it is not null, then you should request it also

so from your snippet above, look at `data.search_metadata.next_results`

**Comment by thegreatmichael** [comment]
also, @isoftmaster, consider closing this issue as there's no bug here.
