### ISSUE TITLE
problem with tweet streaming 

### ISSUE THREAD

**Issue by vickydasta** [ttezel/twit#269]
i got the following errors while using the stream API.

```
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:363:17)
```

**Comment by ttezel** [comment]
what version are you using? Does this issue occur with the latest version of twit for you? (`npm update twit` to get it).

**Comment by vickydasta** [comment]
i'm currenly using 
npm: 3.8.3
node: v5.10.1

**Comment by vickydasta** [comment]
it's silly, i've figured out the problem, you can close this issue, it's just the 
```timeout_ms: 60*1000,``` 
i was forgot to put `,`. my bad :(

**Comment by rert** [comment]
@vickydasta please close the issue if it solved your problem!

**Comment by Brideau** [comment]
@rert @ttezel I receive the same error and am about to try the fix mentioned above. Why _do_ you need the trailing comma, though? Or is that just a typo in the docs?
