### ISSUE TITLE
Allowing to catch multiple events with one listener

### ISSUE THREAD

**Issue by pixeldesu** [ttezel/twit#271]
I'm currently working on a Twitter client and I want to simplify the way of fetching interactions through the API.

As they consist of multiple user events, I'd like to know if there is a way to write one event listener in the following way:

```
stream.on(['favorite','retweet'], function (eventMsg) {
  //...
})
```
...instead of writing several single listeners for these events.

**Comment by ttezel** [comment]
Hi @pixeldesu, there are a few ways to achieve what you want.
The easiest way I can think of right now is actually for you to listen to the `message` event. Then you can check `eventMsg` to see whether it's a favorite or retweet event. If it's not, you discard it.

The return value of `.stream()` is just an [EventEmitter](https://nodejs.org/api/events.html#events_class_eventemitter), and node doesn't provide a native API for adding a list of event handlers, like you're trying to do above. However, you can use an external library such as [EventEmitter2](https://github.com/asyncly/EventEmitter2) to get a different implementation of EventEmitters that allows you to listen for wildcard events or a list of events like you are above. However I haven't actually used that library myself so I can't vouch for it :)

**Comment by ttezel** [comment]
lmk if those approaches don't work!

**Comment by pixeldesu** [comment]
Thanks for the tip!

I managed to do it with looping through a list with events and create handlers for each of them! As the return data is mostly the same I did it that way!
