### ISSUE TITLE
direct_message not working

### ISSUE THREAD

**Issue by rishigb** [ttezel/twit#276]
I have been trying to listen on to 'direct_message' event. I am unable to get any information using this with 'user' stream. Has someone here worked with this before? Could you share a working code? Thanks!

**Comment by rert** [comment]
Hi, This has been working for me.
`var stream = t.stream('user');
//where t is Twit object
stream.on('direct_message', function (data){
	console.log(data.direct_message.text);
});`

**Comment by rert** [comment]
Hi @rishigb , This has been working for me.
``` JavaScript
var stream = t.stream('user');
//where t is Twit object 
stream.on('direct_message', function (data){ 
    console.log(data.direct_message.text);
});
```
Note: Your app need to have direct_message access.

**Comment by rishigb** [comment]
@rert thanks! It's funny, two applications, same permissions, one works, other doesn't. Closing this 'issue' for now. (Should have tested it better). Thanks!

**Comment by hoodsy** [comment]
@rishigb how long did it take for the permissions change to propagate for you?

I've waited ~3 hours, and am listening to all events, and got a new auth token.. still no DMs in the stream.
