### ISSUE TITLE
How to get userid from screen_name

### ISSUE THREAD

**Issue by sapkal-manish** [ttezel/twit#281]
I have screen name of the twitter account of my users. and I want to get tweets of them. but you have api for streaming (e.g. T.stream('statuses/filter', { follow: ["1","2"] } ) ) which accept userid. How Do I get userid from screen_name? It is very urgent for me. Thanks

**Comment by paliitr** [comment]
Suppose you are getting the user name from tweet['user']['screen_name'], instead of that use tweet['user']['id_str'] for getting the user_id.

**Comment by sapkal-manish** [comment]
But how to get tweet? I have just screen_names of my friends, and I want to get all tweets of them.

**Comment by sapkal-manish** [comment]
Actually I want to do as follows.

var Twit = require('twit')
var T = new Twit({
  consumer_key:         '...',
  consumer_secret:      '...',
  access_token:         '...',
  access_token_secret:  '...',
  timeout_ms:           60*1000,  // optional HTTP request timeout to apply to all requests.
})

var screennames = ['friend1','friend2','friend3'....] 
var stream = T.stream('statuses/filter', { follow: screennames });
stream.on('tweet', function (tweet) {
    console.log(tweet)
});

**Comment by paliitr** [comment]
For getting the tweets which were posted earlier, you need to do a RESTful API call.

**Comment by sapkal-manish** [comment]
@paliitr You cann't get my question. I need all tweets made by friends in real time (I think it should be with streaming), But I have just screen_names of my friends, and _**stream('statuses/filter')**_ need userid in follow parameter. So My question is How do I get userids of that screen_names? That I have explained in my example above. Now another problem is comma separated string of userid also not working in _**stream('statuses/filter')**_

**Comment by super-ienien** [comment]
@sapkal-manish You should read the docs before asking questions because everything is explained. Or go on stackoverflow. Here It's not the good place to ask for help. Next time search by yourself if your question is urgent or be very polite (especially when it's a simple problem like this one).

From twitter REST API doc : 

> https://dev.twitter.com/rest/reference/get/users/lookup

From Twitt doc : 

> Any Arrays passed in params get converted to comma-separated strings

**Comment by ttezel** [comment]
@sapkal-manish What @super-ienien said is correct. In order to get a user_id from a screen_name, you can use the REST API.

**Comment by sapkal-manish** [comment]
@super-ienien, Sorry for my bed English. It all happens due to this only. I have already raise question on stackoverflow as @super-ienien has suggested. you can check it [here](http://stackoverflow.com/questions/37965221/how-to-get-tweets-from-the-users-in-node-js). 
Once again, really very sorry for any inconvenience to you and @ttezel. Now I am going to open a new issue. here is the [link](https://github.com/ttezel/twit/issues/282).
