### ISSUE TITLE
Security Vulnerabilities (NSP) - dependency upgrade

### ISSUE THREAD

**Issue by YasharF** [ttezel/twit#288]
`nsp check`

Package:hawk
Installed: 2.3.1
Vulnerable: < 3.1.3 || >= 4.0.0 <4.1.1 
Patched: >=3.1.3 < 4.0.0 || >=4.1.1
Path: twit@2.2.4 > request@2.58.0 > hawk@2.3.1
More Info: https://nodesecurity.io/advisories/77

**Comment by YasharF** [comment]
It looks like request needs to be updated to the latest version.

**Comment by YasharF** [comment]
Will be fixed by https://github.com/ttezel/twit/pull/260

**Comment by ttezel** [comment]
As of twit `v2.2.5`, we use request @ ^2.68.0 so this should be fixed
