### ISSUE TITLE
Twitter stream on follow follows self

### ISSUE THREAD

**Issue by Nulimitz** [ttezel/twit#294]
Here is my code

console.log('the bot is starting');

var twit = require('twit');
var config = require('./config');

var T = new twit(config);

// Setting up a user stream
var stream = T.stream('user');

// Anytime someone follows me
stream.on('follow', beingFollowed);

function beingFollowed(eventMsg){
	console.log(eventMsg.source.id + " followed you!")

	var friend = eventMsg.source.id

	T.post('friendships/create', { id: friend }, tweeted);
	
	//var screenName = eventMsg.source.screen_name
	//tweetIt('@' + screenName + ' do you like unicorns?');
}

the problem is that when I run node bot.js it says I am following myself in the console. What am I doing wrong? Should i run a check to see if the user id is my id, then not try and follow the user. Something like 

function cantFollowMe(user, friend) {
	if user.profile.id = the followers user id
}

**Comment by nartcan** [comment]
Did you resolve the issue?

**Comment by Nulimitz** [comment]
Hi nartcan, yes I ended up comparing the sceenName variable to mine

var friend = eventMsg.source.id
var screenName = eventMsg.source.screen_name
	
	var params = {
		user_id: friend,
		follow: true
	}
	
    if(friend != stream && screenName != 'yourtwiitername') {
        //add the user
});
    }

**Comment by codeMeHtm** [comment]
``` javascript
var params = {
    user_id: friend,
    follow: true
}

if(friend != stream && screenName != 'yourtwiitername') {
    //add the user
});
}
```
