### ISSUE TITLE
followers/ids doesn't render everything.

### ISSUE THREAD

**Issue by Vancer** [ttezel/twit#321]
Hello there, when i use 

T.get('followers/ids', { screen_name: 'usernamehere' },  function (err, data, response) {
  console.log(data)
})

It returns with ID's but it says  **... 259 more items ],** , how can i print them ALL out ?

**Comment by chgibb** [comment]
This is a limitation of console.log. Use: 
```javascript
T.get('followers/ids', { screen_name: 'usernamehere' }, function (err, data, response) {
console.log(JSON.stringify(data,undefined,4));
})
```
to stringify (that is, convert the JSON structure to a string) and then log that.

**Comment by Vancer** [comment]
Thanks ! 💃
