### ISSUE TITLE
OnStream Tweet Parse.

### ISSUE THREAD

**Issue by Vancer** [ttezel/twit#324]
Well what i'm trying to do here is wait until someone tweets and has the word programming in the tweet after that console.log an alert that someone did. After that I want to get the tweet that this person tweeted, but not the whole information just the tweet itself as in tweet.text. I tried having tweet.text console logged, but it returns with undefined, I guess its a JSON object and needs to be parsed any help ?

`var Twit= require('twit');

var config= require('./config');
var T = new Twit(config);

var stream = T.stream('statuses/filter', { track: 'programming'});

stream.on('tweet',updateNews);

function updateNews(err, data, response, tweet){
	console.log("Someone said programming");
	T.get('search/tweets', { q: 'programming'}, function(err, tweet, response) {
		console.log(tweet)
})
}
`

**Comment by chgibb** [comment]
I believe it should be the following:

```javascript 
var Twit= require('twit');

var config= require('./config');
var T = new Twit(config);

var stream = T.stream('statuses/filter', { track: 'programming'});

stream.on('tweet',updateNews);

function updateNews(err, data, response, tweet){
console.log("Someone said programming");
console.log(tweet)
}
```javascript 

You're creating a new request within the stream callback and then logging that response instead of logging the response from the stream.

**Comment by Vancer** [comment]
Here is what it returns:
Someone said programming
undefined

**Comment by chgibb** [comment]
Looking at the readme under streaming I found this snippet. 
```javascript 
//
//  stream a sample of public statuses
//
var stream = T.stream('statuses/sample')

stream.on('tweet', function (tweet) {
  console.log(tweet)
})
```

Your updateNews function should then take a single argument, which I believe will be the entire tweet object. You will probably have to access the tweet text through it's text member. You can stringify the argument to be sure.

**Comment by Vancer** [comment]
Can you explain please I don't get it

**Comment by Vancer** [comment]
Work's like a charm, here is the source incase someone was wondering.
```
var Twit= require('twit');

var config= require('./config');
var T = new Twit(config);

var stream = T.stream('statuses/filter', { track: 'programming'});

stream.on('tweet', function(tweet){
	console.log('Did we just find a geek: ');
	console.log(tweet.text);
});

```
