### ISSUE TITLE
how to get the twitter screen / profile banner / photo

### ISSUE THREAD

**Issue by scankannan** [ttezel/twit#330]
I am wondering what is the best possible way to extract the twitter screen / profile banner

**Comment by jimmybrawn** [comment]
maybe you find your answer here?
https://dev.twitter.com/rest/reference/post/account/update_profile_image

**Comment by ttezel** [comment]
Hi @scankannan, questions related to "best usage of the Twitter API" are better asked on the Twitter dev site (https://dev.twitter.com/), I can't answer all the questions related to how to use the API; there are too many of them :)
