### ISSUE TITLE
Use setInterval call twit from another module

### ISSUE THREAD

**Issue by spences10** [ttezel/twit#331]
I'm not sure if this is relating to `twit` or `node` [more than likely me] but when I try to call `twit` from another module as a search I get the same result. But if I call `twit` within the same module using `setInterval` I don't get the issue...

Example:
```
let s = require('./helpers/search')

var a = function() {
  s.id()
}
a()
```

Output will be a twitter id `8301896xxxxxxxxxx5` from the `search.js` module

If I call the function via `setInterval(a, 1000)` I'll get the same `Id`

The module being called is a straight forward `node` module:

```
let T = require('./T')
let p = require('./twitParams')

var tweetId = function() {
  T.get('search/tweets', p)
    .catch(function(err) {
      console.log('caught error', err.stack)
    })
    .then(function(result) {
      console.log(result.data.statuses[0].id_str)
    })
}

exports.id = tweetId;
```

I have tried using `node-schedule` as well and everything returns that same `Id` like the import needs to be reinitialised each time it is called.

**Comment by chgibb** [comment]
In your promise resolution you're always printing the id_str of element 0 of the statuses array. This is likely the cause.

Do you have the full code on Github?

**Comment by spences10** [comment]
@chgibb sure, I have it here https://github.com/spences10/node-module-testing

But not done much with it since hitting this

**Comment by spences10** [comment]
Even if I change the `data.statuses[0]` to use unique-random-array it will still return the same Id

The example here was the most straightforward way I could put it.

**Comment by ttezel** [comment]
You have to instantiate an instance of the module, then you can call `.search` on the instance. There is no known race condition in the twit module.

**Comment by spences10** [comment]
Welcome back @ttezel !

I wasn't sure this repo was still being maintained 🙃 

![image](https://user-images.githubusercontent.com/234708/27193875-6a9f8bbe-51f8-11e7-9dd2-5fa27eb8efba.png)

**Comment by ttezel** [comment]
haha thanks @spences10, I was out of the open source world for a bit there :)
