### ISSUE TITLE
How to match an exact phrase using the query operators

### ISSUE THREAD

**Issue by jzos** [ttezel/twit#333]
To reference, https://dev.twitter.com/rest/public/search, I want to be able to query a specific phrase. How can I do that using:

var stream = T.stream('statuses/filter', { track: 'happy hour', language: 'en' });

If I do that, it gives me anything matching happy and hour in the post, where I just want the exact phrase, happy hour.

In the example below it references to do this by putting double quotes around the phrase, but it seems like this does not work if you put double quotes in the single quote string, shown above.

“happy hour” | containing the exact phrase “happy hour”. 

If there is something I'm missing or a work around, I'd appreciate it. Thanks for all your hard work on this and thanks in advance!

Jaime

**Comment by chgibb** [comment]
While I am not familiar with the particular endpoint you're trying to query, if it says to use double quotes then you will likely have to do the following:
```javascipt
var stream = T.stream('statuses/filter',{track: '\"happy hour\"', language: 'en'});
```

Javascript does not differentiate between single and double quotes except where nesting is concerned. Both forms are interpreted as the same string. Escaping double quotes inside of your query string will ensure that the double quotes get submitted to the endpoint.

**Comment by jzos** [comment]
Thanks @chgibb! I already tried that and it didn't work. I need to read more on https://dev.twitter.com/streaming/reference/post/statuses/filter and see if there's a way to use the query operators to get the result I need. I need to look at the code library and see how it's pushing out the request, so maybe there's something I can do there, but thanks for responding so quickly! I appreciate it!

**Comment by jzos** [comment]
**Update on this!** 

https://dev.twitter.com/streaming/overview/request-parameters#track

> Exact matching of phrases (equivalent to quoted phrases in most search engines) is not supported.

So I guess that answers the question. It's not supported within the API for the Streaming API Request Parameters.

**Comment by chgibb** [comment]
You could always filter results as they come in in order to match find tweets which match your phrase.

**Comment by jzos** [comment]
@chgibb absolutely! Going to write a replay script to go through mongo and filter those out. It was just easier, of course, to just try to query it directly. Thanks again for your help!

**Comment by chgibb** [comment]
No worries @jzos. If you believe you have a solution, please close this issue.
