### ISSUE TITLE
No way to get the text of a tweet

### ISSUE THREAD

**Issue by NITEHAWKDevs** [ttezel/twit#335]
I am trying to console.log() the text of the tweets that my bot is retweeting, but there doesnt seem to be a way to get the text... anyone know?

**Comment by chgibb** [comment]
What's your solution so far?

**Comment by NITEHAWKDevs** [comment]
I have tried so many things that I thought would work and none have worked so far

**Comment by chgibb** [comment]
Can you post some code examples?

**Comment by NITEHAWKDevs** [comment]
```js
function BotRetweet() {

	var query = {
		q: TWITTER_SEARCH_PHRASE,
		result_type: "recent"
	}

	Bot.get('search/tweets', query, BotGotLatestTweet);

	function BotGotLatestTweet (error, data, response) {
		if (error) {
			twitlog(`${botname} Bot could not find latest tweet, : ` + error);
		}
		else {
			var id = {
				id: data.statuses[0].id_str
			}

			Bot.post('statuses/retweet/:id', id, BotRetweeted);
			
			function BotRetweeted(error, response) {
				if (error) {
					twitlog(`${botname} Bot could not retweet: ` + error);
				}
				else {
					twitlog(`${botname} Bot retweeted : ` + data);
					 bot.guilds.get('280556103694155796').channels.find('name', 'twitter').sendMessage(`${botname} Bot retweeted : ` + id);

				}
			}
		}
	}
	

	setInterval(BotRetweet, 10*60*1000);
}
```
That is the whole function

**Comment by chgibb** [comment]
What's the output from this snippet?

**Comment by NITEHAWKDevs** [comment]
It outputs an error aswell as [object Object]

**Comment by chgibb** [comment]
Could I see the full code? Have you tried to stringify the data object to see if  text property exists?

**Comment by NITEHAWKDevs** [comment]
I will send you the full code when I get home, and I remember there being a way to get the text of a tweet

**Comment by ttezel** [comment]
If you inspect the JSON object returned in the response, every tweet object has a `text` property that contains the tweet's text.
