### ISSUE TITLE
How can I get all the tweets of a specific user? 

### ISSUE THREAD

**Issue by Sara3** [ttezel/twit#338]

**Comment by ezequias** [comment]
Here's my code (using mocha):

 it.only('ALL tweets from @ErikaFrossard', function (done) {
        var count = 0;
        var tweets;
        var max_id = -1;
        var name = 'ErikaFrossard';
        this.timeout(30000);
        T.get("statuses/user_timeline", { screen_name: name, count: 200}, function (err, data, response)
        {
            console.log('Tweets from @' + name);
            printTweets(data);

            max_id = data[data.length - 1].id_str;
            async.whilst(function () {return max_id;}, function (callback)
            {
                T.get("statuses/user_timeline", { screen_name: name, count: 200, max_id: max_id}, function (err, data, response)
                {
                    printTweets(data);
                    if (data.length > 1)
                    {
                        max_id = data[data.length-1].id_str;
                    }
                    else
                    {
                        max_id = 0;
                    }
                    callback();
                });
            }, function (err) {
                console.log("all done\n" + "Tweets: " + count);
                done();
            });
            function printTweets(data)
            {
                 for (var i = 0; i < data.length; i++)
            {
                console.log(count + ' ' + data[i].text);
                count++;
            }
            }
        });
    });

**Comment by ezequias** [comment]
Some tweets are missing. I don't know why. 🤔

**Comment by Sara3** [comment]
@ezequias thanks,  what did u use mocha for? (new to this)

**Comment by ezequias** [comment]
Yes @Sara3 and for sincronize the aschinc call I used https://caolan.github.io/async/

Mocha is awesome! :muscle:

add: 
var async = require('async');
var whilst = require('async/whilst');

**Comment by Sara3** [comment]
@ezequias  thank you, thank you!
