### ISSUE TITLE
Error: unexpected end of file at Zlib._handle.onerror (zlib.js:370:17)

### ISSUE THREAD

**Issue by webolizzer** [ttezel/twit#352]
Hello, I just see an error message:

```events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17)
```

The App before is running without errors since ca. 5 hours

Thanks

**Comment by bo01ean** [comment]
I am also getting this error:

```
Plitvice-1 { Error: incorrect header check
Plitvice-1     at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
Plitvice-1 { Error: incorrect header check
Plitvice-1     at Zlib._handle.onerror (zlib.js:370:17) errno: -3, code: 'Z_DATA_ERROR' }
```

**Comment by bo01ean** [comment]
https://github.com/ttezel/twit/pull/353

**Comment by klaveren** [comment]
This happened to me, normally when I was inside a looping it would open many connections simultaneously. I started using setInterval () with 1000 milliseconds, and I did not have this problem any more.

Another thing I noticed, is that when the internet connection oscillates, it can give this same error. I honestly do not know very well what it means but solved it.

**Comment by dantheloung** [comment]
Hi, I got this error last night. Program was running fine for a few hours, then threw up this error.
I added in an error listener for the stream.on() which I didn't have at the time of the error.
That just triggered, then froze the app.
I tried stopping and starting the stream again, but it just constantly threw the error back.
The error persisted until I closed and reopened terminal, then it started working again.
I thought I'd messed up my twitter app, but seems to be something local.


BTW:
I'm a very amateur coder so it's likely I'm doing something drastically wrong. - I'm writing a tweetbot that's listening out for a specific tweet, I'm saying stream.on, but do I need a stream.stop() somewhere, or is it ok to leave it on?

**Comment by kud** [comment]
Related https://github.com/ttezel/twit/issues/300

Workaround: https://github.com/ttezel/twit/issues/300#issuecomment-279205874

**Comment by bo01ean** [comment]
I think we are getitng this error for different reasons:
In my case a 4XX code is being thrown and twit still tries to connect (which will not work)
Your case seems to be related to a legit zlib parse error which will or will not happen on subsequent events.

**Comment by webolizzer** [comment]
Ok i know the problem. This error will come if something in the app like a for loop does block for long time the script flow.
