### ISSUE TITLE
How can I get a tweet by its ID?

### ISSUE THREAD

**Issue by aleshh** [ttezel/twit#370]
I'm streaming tweets, but I want to access each tweet after 5 minutes to see how many likes it's gotten. So I've got setTimeout inside my stream, and now I need to re-fetch the status:

```
T.get('statuses/show/:id', { id: statusId }, function(err, data, response) {
  console.log('test err     : ' + err )
  console.log('test data    : ' + data
  console.log('test response: ' + response )
})
```

The problem is that the ID is an 18-digit number and JavaScript rounds it off, so I get an `Error: No status found with that ID.` I have the id as a string right there, but the [Twitter API](https://dev.twitter.com/rest/reference/get/statuses/show/:id) wants a number. Is there a way to do this?

**Comment by aleshh** [comment]
Oh, duh: this works perfectly well if I pass `id_str` to statusId.

**Comment by imtechieraj** [comment]
@aleshh  Thanks. It's work. :)
