### ISSUE TITLE
Replying to a specific tweet

### ISSUE THREAD

**Issue by vineethsagar** [ttezel/twit#374]
I am unable  to send repy to a specific tweet  filtered by hashtag The code is just updating the status  but it is not replying to that tweet here is  the code 
var stream_public = T.stream('statuses/filter',{track :'#miniproject528',language :'en'});

stream_public.on('tweet',replytotweet);
 function replytotweet(tweet){
   var username = tweet.user.screen_name;
   console.log(username);
   console.log(tweet.text);
   var tweetid = tweet.id;
    console.log(tweetid);
   var idnew = tweet.user.id_str;
   console.log(idnew);
   var k =Math.floor(Math.random()*100);
   var msg = '@'+username+' ' +'Replied to user'+ k;

  T.post('statuses/update',{
    status :msg, 
    in_reply_to_status_id :tweet.user.id_str
  },function(err,data,response){
    if(err){
      console.log(err);
    }
      else{
          console.log(data);
      }
    
  }
  );

**Comment by ernerock** [comment]
haven't tested  but it seems like you are using the user_id rather than the status_id

**Comment by ttezel** [comment]
Yup @ernerock is right :)
