### ISSUE TITLE
A function creates my tweet. How do I post it?

### ISSUE THREAD

**Issue by selimsaukkomaa** [ttezel/twit#380]
I have a function that creates my tweet as a variable that I want to post with T.post. However, I have no clue how to get that tweet out of the function into the T.post. Placing T.post within the function does not seem to help either. 

As you may or may not tell, I'm very much a beginner in JS and as such this might be some super basic thing that I just don't know.

**Comment by spences10** [comment]
Hi @selimsaukkomaa 

I have a couple of resources for you here:

https://github.com/amandeepmittal/awesome-twitter-bots

I'd go with the `Create a Simple Twitter Bot` examples, they really helped me out.

Then once you are comfortable with that then there a fair bit of documentation I put together on how to use the `twit` module:

https://github.com/spences10/twitter-bot-playground#twitter-bot-playground

Good luck 👍
