### ISSUE TITLE
New 280 characters in Twitter

### ISSUE THREAD

**Issue by maziyarpanahi** [ttezel/twit#383]
Hi,

The only place that I could find with hard-coded 140 character is bot.js in examples. Soon Twitter will make this 280 characters open to everyone and I think this file should be increased to 280 as well.

Best,
Maziyar

**Comment by varjmes** [comment]
For anyone coming to this issue (like me) who doesn't know how to get 280 chars.

Twit doesn't put any restrictions on character count. You can have longer tweets by doing the passing the following param to the Twitter API.

```javascript

  T.post('statuses/update',
    { status: 'wow so many characters lol', 
       tweet_mode: 'extended'
    }, (err, data, response) => {
      console.log(tweet)
      console.log(tweet.length)
      if (err) throw err
  })
```

**Comment by maziyarpanahi** [comment]
thanks @varjmes! Also, in Streaming API there is a field named extended_tweets which has multiple media, video and a filed named `full_text`. This field contains the full text if the text is more than 140 characters.

**Comment by maziyarpanahi** [comment]
ping @ttezel 
Very nice seeing you back! If you don't mind me I can create a pull request for changing the bot.js?
