### ISSUE TITLE
Operators don't work on Stream

### ISSUE THREAD

**Issue by Shaderboy** [ttezel/twit#389]
Some of the [basic operators](https://developer.twitter.com/en/docs/tweets/rules-and-filtering/overview/basic-operators) don't seem to work with the streaming 'statuses/filter' endpoint. Specifically, :( and :), though there may be others.

**Comment by maziyarpanahi** [comment]
I don't think the basic operators are for streaming. I think they are for search APIs. Anything possible for streaming is listed here: (it has track as everything will be assumed "OR")
https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/basic-stream-parameters

**Comment by Shaderboy** [comment]
Sadly, I think you're right. Thanks.
