### ISSUE TITLE
Count does not always return the required amount of tweets

### ISSUE THREAD

**Issue by almostprogrammer** [ttezel/twit#396]
I've noticed that sometimes, I don't get a requested amount of tweets. It happens occasionally. Is it a Tweeter's issue or is there something wrong with a package?

```
const Twit = require('twit');

const twit = new Twit({
  consumer_key: ' xxxx',
  consumer_secret: 'xxxx',
  access_token: 'xxxx',
  access_token_secret: 'xxxx',
});

module.exports = query => {
  return new Promise((resolve, reject) => {
    twit.get('search/tweets', query, (err, data, response) => {
      resolve(data);
    });
  });
};
```

**Comment by almostprogrammer** [comment]
The query parameter that I pass is an object:

```
      let word = 'something';
      const data = {
        q: word, 
        count: 4, // number of twits
      };
```

**Comment by MegaCha0s** [comment]
Hope this works:

```
T.get('search/tweets', { q: 'banana since:2011-07-11', count: 100 }, function(err, data, response) {
    console.log('Number of tweets: ', data.length);
});
```

**Comment by ttezel** [comment]
This isn't a twit issue - twit just passes along the request parameters to Twitter and it's up to Twitter to return up to `count` tweets. There's no guarantee that you'll get `count` tweets, eg. if your search query matches less than `count` tweets you will get less than `count` tweets.
