### ISSUE TITLE
Change the client name

### ISSUE THREAD

**Issue by chasset** [ttezel/twit#397]
Hello,

When you request a tweet using `T.get('statuses/show', { id='210462857140252672'}, …)` for example, the result that you receive is a data structured in JSON. In these data, there is a field called `source`. 

How can I control the value of this field `source` when I post a tweet using your client
 and the method `T.post('statuses/update', { status: 'hello world!' }, …`?

Best regards,

Pierre-Olivier

**Comment by maziyarpanahi** [comment]
Hi @chasset,

Unfortunately within the Twitter API - it does not support custom source value in a Tweet object. Only the application that sent the Tweet set this information.
Here is the list of parameters can be set in each status before posting it:
https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-statuses-update

Cheers,
Maziyar

**Comment by chasset** [comment]
Alright. I understand how it works now. Cheers
