### ISSUE TITLE
stream.stop() is not closing the connection with Twitter

### ISSUE THREAD

**Issue by abuamt** [ttezel/twit#399]
function twitter(key) {
    var stream = client.stream('statuses/filter', {
        track: key,
        language: 'en'
    });
    stream.stop();
    stream.on('tweet', function(tweet) {
        console.log("tweet", tweet);
    });
}

Here key will be different in different function call. So every time I want to stop and start the stream. But here, after connecting stream to twitter, stream will not stop and connect with new keys.

**Comment by DanishFayaz** [comment]
Same issue, stream.stop() doesn't work at all and even after that I keep receiving tweets. I've debug the code and went in the source library, following is the source method for stop:

`StreamingAPIConnection.prototype.stop = function () {
  // clear connection variables and timeout handles
  this._resetConnection();
  this._resetRetryParams();
  return this;
}
`

I've went into _resetConnection() as following:

```
StreamingAPIConnection.prototype._resetConnection = function () {
  if (this.request) {
    // clear our reference to the request instance
    this.request.removeAllListeners();
    this.request.destroy();
  }

  if (this.response) {
    // clear our reference to the http.IncomingMessage instance
    this.response.removeAllListeners();
    this.response.destroy();
  }

  if (this.parser) {
    this.parser.removeAllListeners()
  }

  // ensure a scheduled reconnect does not occur (if one was scheduled)
  // this can happen if we get a close event before .stop() is called
  clearTimeout(this._scheduledReconnect)
  delete this._scheduledReconnect

  // clear our stall abort timeout
  this._stopStallAbortTimeout()
}

```
All the three params, request, response, parser and _scheduledReconnect appear as undefined. Can anyone please check what's causing this and why the stop function isn't stopping the stream.

**Comment by DanishFayaz** [comment]
Can you explain your usecase a bit more, I may be able to help

**Comment by ttezel** [comment]
looks like you're creating the stream, stopping it, then listening on tweets? I don't think this code will stream any tweets. You probably want to stream some tweets, then call `.stop()` later. Feel free to reopen if your code isn't stopping the stream when called once - it should be.
