### ISSUE TITLE
Stream dies after a couple hours

### ISSUE THREAD

**Issue by martinolmos** [ttezel/twit#406]
Hi, 

I've followed [this](https://aws.amazon.com/blogs/big-data/building-a-near-real-time-discovery-platform-with-aws/) tutorial to deliver tweets to an Amazon S3 bucket.

Everything works fine for 2 or 3 hours, but eventually the stream stops and doesn't reconnect again. I can't find any error messages in application.log.

Any clues what might be happening?

**Comment by dandv** [comment]
I've had streams run for weeks with [twitter-lite](https://github.com/draftbit/twitter-lite) without issues.
