### ISSUE TITLE
Any way to exclude retweets from search?

### ISSUE THREAD

**Issue by pythoncreate** [ttezel/twit#409]

**Comment by Tom-Hudson** [comment]
I would also like to know how to do this!

**Comment by maziyarpanahi** [comment]
Hi, have you tried to add `-filter:retweets` to your query?
This link might be useful: http://thesocialchic.com/2013/04/26/how-to-master-twitter-search/

**Comment by pythoncreate** [comment]
yep that's it...i added a filter like this:

`const filterData = (tweet) => {
    return ((!tweet.retweeted)
        && !(tweet.text.includes('RT @')
        && ((tweet.in_reply_to_status_id) === null)));
  };`

**Comment by maziyarpanahi** [comment]
@pythoncreate awesome! Happy to hear that. Would you mind closing the issue, many thanks :)

**Comment by pythoncreate** [comment]
sure thing thanks!

**Comment by Tom-Hudson** [comment]
@pythoncreate, this doesn't actually resolve the issue. You are filtering the tweets in your code. Not having filtered tweets sent back from the API...

...@maziyarpanahi - how do we add `-filter:retweets` to the 'query'? Can you provide a working example?
