### ISSUE TITLE
statuses/filter stream won't work when follow ids count is larger then 625

### ISSUE THREAD

**Issue by pantchox** [ttezel/twit#413]
Hi 
```
var stream = T.stream('statuses/filter', {follow: '123,456,...});
```

when having the follow key value of over 625 ids, it just connects and try to reconnect again.

IN:
https://developer.twitter.com/en/docs/tweets/filter-realtime/api-reference/post-statuses-filter.html

it is mentioned that you can track up to 5000 ids.

I assume this is a bug in twit?

thanks for the great lib!

**Comment by maziyarpanahi** [comment]
well the 5000 has never worked if you do a little search. It always stops around 1200 IDs due to HTTP header is to long! 
As for the Stream API and tracking IDs by twit, I have been using it with 6000 IDs (separate apps) and it works perfectly.
Listen to the `error` and see why it disconnects.

**Comment by pantchox** [comment]
Hi thanks for replying.
There is not error what so ever, it just connect and then reconnect and continue like this with no error.
as for the HTTP header, i think behind the scenes its POST so it should work.

You mentioned using separate apps, can you maybe describe what is your architecture of what it is exactly you are doing? i think we can all benefit from it.

Thanks.

**Comment by maziyarpanahi** [comment]
I am not sure if the length limit for POST is from this library (request.js) or Twitter but you can find posts like this all over the place:

https://twittercommunity.com/t/changes-to-the-follow-stream/91273/7

https://twittercommunity.com/t/streaming-api-error-503-after-increasing-number-of-followed-ids/22172/2

https://github.com/desmondmorris/node-twitter/issues/236

Now, you can have as many applications as you want as long as you maintain one connection to each. Also following the rules of connecting and reconnecting for each. 

Therefore, the workaround is if you have 5000 UserIDs or more which there is no way to follow them all at once by one application, create multiple apps and assign about 1000-1200 IDs to each and start them all together. That's what the majority of people are doing as a work around.

Hope this helps

**Comment by pantchox** [comment]
Great! thanks for that.
one last question, from what i remeber reading here and the twitter community basically you can't have all your application use the stream and from the same IP? did you encounter any limitations or best practices you noticed from their services?

thanks!

**Comment by maziyarpanahi** [comment]
No at all! You can have many applications running streaming APIs from the same IP address. Just be careful about one connection only for each application and the reconnect policy (waiting 30s-40s and extend it each time if it couldn't connect). Then your IP wouldn't be blocked for too many requests since you have many apps and they all are going to re-connect at some point if there is a problem in network or Twitter services.

**Comment by pantchox** [comment]
amazing thanks!
checkout my twitter archiver, you may find it useful https://github.com/pantchox/Twitark

**Comment by maziyarpanahi** [comment]
@pantchox great! thanks for the link. Would you please close this issue? Many thanks :)
