### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by dandv** [ttezel/twit#414]
This looks like a solid library, but it's fallen behind the times a bit (see #411, #412). Also, there haven't been any commits in more than half a year.

I've found a very promising replacement library, [twitter-lite](https://github.com/Preposterous/twitter-lite), but it doesn't support streams yet. However, it's tiny (<1KB), uses native Promises and works on both the client and the server.

**Comment by ttezel** [comment]
Closing this issue - you're free to use another library if it meets your needs better
