### ISSUE TITLE
some api will be deprecated.

### ISSUE THREAD

**Issue by bankzxcv** [ttezel/twit#416]
Hi guys.
some api will be deprecated will you change to the new?
https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/get-messages

**Comment by maziyarpanahi** [comment]
I am not sure if this happens anytime soon, but I see if I can get external contributor from the owner and help with deprecations.

**Comment by ttezel** [comment]
Yeah some APIs are being deprecated in favor of the new Account Activity API. It looks like a lot of the APIs are still going to stick around though. When the Account Activity API becomes generally available I can get to implementing, but right now it's only available to premium and enterprise users.
