### ISSUE TITLE
REST and Stream APIs are going to be discontinued on June

### ISSUE THREAD

**Issue by Balaji-Ramasubramanian** [ttezel/twit#422]
Hi Developer,
As per Twitter announcement at [Twitter Developer Page](https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/overview ), They are going to discontinue the REST and Stream API of Twitter by June 19, 2018. Any apps that use these APIs after that time period will be getting an error response. Do you have any plans for updating this npm module to support the latest Account Activity API?

**Comment by loljoho** [comment]
I don't see anything about the REST APIs though?

> The Account Activity API will replace the User streams and Site streams APIs. Additionally, we plan to sunset those APIs on Tuesday June 19, 2018.

Does that not refer only to the Stream APIs?

**Comment by maziyarpanahi** [comment]
Only the User Streams and Site Streams are going to be deprecated not all the rest of Streaming APIs including status/filter and status/sample.

But unfortunately, that is on its way as well as Twitter wants to change all its Streaming APIs.

https://trello.com/c/dwCWo22Y/21-replace-statuses-filter-and-statuses-sample-with-more-flexible-endpoints?menu=filter&filter=filter

PS: I don't see any sign that this library would go back to active development. You can consider it as not maintained.

**Comment by ttezel** [comment]
This module will support the REST and Streaming APIs as long as possible, and once the Account Activity API is generally available I'll see if I can get it implemented (also will be totally open to pull requests 😄). Right now it looks to be only available to paid customers
