### ISSUE TITLE
Retweet Stream not working

### ISSUE THREAD

**Issue by Tchekda** [ttezel/twit#428]
Hi,
I am looking for a way to stream the retweets without text, because stream.on('quoted_tweet') don't cover that.
So i tried stream.on('retweeted_tweet') / stream.on('retweet_tweet') / stream.on('retweeted') / stream.on('retweet') but any of them is working.
I'm actually using stream.on('tweet') and i check if it's a retweet and if i am the source or the receiver.
So i would like to know if a special userstream exist to do that?

**Comment by DanishFayaz** [comment]
I'd recommend that you should stream on 'tweet' cause a Retweet is also itself a tweet. So whenever a new tweet comes. Pass its text with a Regex like (^(RT|rt)( @\w*)?[: ]) so you can classify the ones which pass through it as a retweet. Cheers.

**Comment by Tchekda** [comment]
Thank k you for your reply @DanishFayaz , I'm already using this method but I was just expecting a specific stream for retweets.
Cheers
