### ISSUE TITLE
Vulnerability issues with a sub dependency

### ISSUE THREAD

**Issue by ooade** [ttezel/twit#429]
Here is a screenshot of the issue made by GitHub:
![vulnerability](https://user-images.githubusercontent.com/11811904/39399926-b3495802-4b1e-11e8-91c5-863ccb95d396.png)

Tracing the graph, I have this:
```
└─┬ twit@2.2.9
  └─┬ request@2.85.0
    └─┬ hawk@6.0.2
      ├─┬ boom@4.3.1
      │ └── hoek@4.2.1  deduped
      ├─┬ cryptiles@3.1.2
      │ └─┬ boom@5.2.0
      │   └── hoek@4.2.1  deduped
      ├── hoek@4.2.1 
      └─┬ sntp@2.1.0
        └── hoek@4.2.1  deduped
```
Updating the request package might fix this :man_shrugging:

**Comment by Ilshidur** [comment]
There is also a vulnerability in `twit@2.2.9 › request@2.85.0 › stringstream@0.0.5` [according to Snyk](https://snyk.io/test/npm/twit/2.2.9?severity=high&severity=medium&severity=low).

**Comment by ChALkeR** [comment]
https://github.com/request/request/pull/2885 landed, so this can be closed now, I think.

**Comment by ttezel** [comment]
Hmm according to snyk, there are currently no known vulnerabilities in the `twit` dependency graph: https://snyk.io/test/npm/twit

**Comment by ttezel** [comment]
@Ilshidur and @ChALkeR all good to close this?

**Comment by Ilshidur** [comment]
@ttezel Yes I believe this issue can be closed now.

**Comment by ChALkeR** [comment]
@ooade That was probably an issue in your [package-lock](https://github.com/ooade/awesome-preact-bot/blob/master/package-lock.json) file, it freezes nested deps. Just updating, deleting, or rebuilding it should fix the issue.
