### ISSUE TITLE
Get old tweets doesn't work

### ISSUE THREAD

**Issue by LuisPaGarcia** [ttezel/twit#430]
I want to get old tweets from an account:

```javascript
const Twit = require("twit");
const T = new Twit({
...
});

T.get(
  "statuses/user_timeline",
  { screen_name: "user_account", count: 10, q: "a until:2018-03-03" },
  function(err, data, response) {
    console.log(data);
  }
);
```

But this get only new tweets. Anybody have an idea to get old tweets based on date? #

**Comment by ttezel** [comment]
Yeah I've found that the Twitter API date filtering doesn't work as expected all the time. Twit passes your query along to the Twitter API so I don't think this is a `twit` issue.
