### ISSUE TITLE
Is it planned to support the new Account Activity API?

### ISSUE THREAD

**Issue by leocabeza** [ttezel/twit#432]
According to Twitter, user streams will be deprecated... ¿soon?.

Source: https://twitter.com/TwitterDev/status/982346370882461696?s=20
New api overview: https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/overview

**Comment by ttezel** [comment]
Hi @leocabeza when it becomes generally available I can get to implementing, but right now it looks like that API is only available to premium and enterprise accounts.
