### ISSUE TITLE
answering to tweets doesn't work properly vol.2

### ISSUE THREAD

**Issue by ChandlerMBing** [ttezel/twit#438]
continuing closed issue #437 

@ttezel OK, so I think the best way to explain is with some screen shots, because that's all the code there is, not counting the `const T  = new Twit({...})`, but that's definitely ok because I'm able to tweet from node but when it comes to replying or retweeting it goes haywire.

Running the callback with a console.log.
<img width="942" alt="screen shot 2018-06-04 at 20 40 36" src="https://user-images.githubusercontent.com/23351348/40917986-9b558df2-6837-11e8-9e6c-96cda0da6dd3.png">
runs once
<img width="562" alt="reply_terminal" src="https://user-images.githubusercontent.com/23351348/40910683-588def18-681f-11e8-9bd3-f7c66c9491d7.png">
running the callback with T.post
<img width="903" alt="reply_post" src="https://user-images.githubusercontent.com/23351348/40910685-58cce6a0-681f-11e8-837a-933416f38c57.png">
runs 4 times and throws an error.
<img width="1392" alt="reply_post_terminal" src="https://user-images.githubusercontent.com/23351348/40910686-590b05a2-681f-11e8-97c7-84c59ef7b0de.png">

**Comment by ttezel** [comment]
Hi @ChandlerMBing I tried to explain this in the other issue - this is not a problem with twit. What's going on here is the tweet content in your tweets is too similar to what you already tweeted, and the Twitter API is blocking this behavior for anti-spam reasons.

**Comment by ChandlerMBing** [comment]
@ttezel yeah, ok, so please explain to me why when  the function runs without the Twit package it runs once but with the package, it runs 4 times? There's only one variable between the two examples, and it is the Twit package. I know what the error is and why it happens, what I wanna know is why the package for some reason replies 4 times to one tweet instead of just once AND the same thing happens with retweets where it tries to retweet the same tweet so obviously it ends up throwing an error.

**Comment by GarkGarcia** [comment]
You might be replying to yourself. I believe the `"tweet"` event also gets emitted when you post a tweet, so, given the context of your code, every time you reply to someone you start an infinite loop of replies to yourself and Twitter blocks it in the fifth duplicate reply.

Please, don't be aggressive to people who are trying to help you.
