### ISSUE TITLE
Reply to tweet is not working

### ISSUE THREAD

**Issue by landau** [ttezel/twit#44]
The following code should result in a reply to a post, but it does not. The tweet goes through successfully, but not as a reply. The id used below was taken from the `id_str` property on the user deacondesperado's tweet. I've included his handle in the status as the api requires.

Any thoughts? 

``` javascript
var data = {
    status: "test with @deacondesperado",
    in_reply_to_status_id: 312188548927348737
};
twitter.post "statuses/update", data, function (err, res) {
});
```

**Comment by Vectormike** [comment]
Oh, I get it now.
