### ISSUE TITLE
How do I get the URL of most recent tweet?

### ISSUE THREAD

**Issue by SirFelolis** [ttezel/twit#440]
I use this module for a discord bot where you can tweet via discord, and I want to link the tweet in discord, but I can't find out how to get the URL of the most recent tweet. Anyone know how?

**Comment by ttezel** [comment]
Hi @SirFelolis, please don't use github issues as a forum - open an issue if you have a particular problem with this package. Thanks :)

**Comment by SirFelolis** [comment]
How am I supposed to solve this issue then?

**Comment by pthieu** [comment]
@SirFelolis: have you found a way to do this?

@ttezel: where would be an appropriate location to ask this question?

**Comment by maziyarpanahi** [comment]
Since the returning Tweets are the same among all ththe libraries and this question is not an issue nor related to this specific library, your best bet is places like StackOverflow or even Twitter community.

**Comment by pthieu** [comment]
Did a look up on the twitter API, for anyone that's stills curious how to do this, you can just use the `id_str` returned from a tweet
and plug it into `https://twitter.com/<this part of the route does not matter>/statuses/<id_str>`
