### ISSUE TITLE
Missing "media_category" parameter when posting media

### ISSUE THREAD

**Issue by gryp17** [ttezel/twit#441]
There doesn't seem to be a way to provide the **media_category** parameter when using **postMediaChunked()**.

Here is a link to the **INIT** endpoint documentation where this parameter is documented: https://developer.twitter.com/en/docs/media/upload-media/api-reference/post-media-upload-init 

This causes the twitter API to treat the file as an image and to apply the **5MB** limit when uploading GIF's instead of the **15MB** limit that twitter uses for GIF's.

**I would suggest adding another parameter "media_category" to the FileUploader.prototype._initMedia function.**

**How to reproduce:**
Try to upload a GIF that is bigger than 5MB

**Workaround:**
Just use the **T.post('media/upload')** function for the **INIT**, **APPEND** and **FINALIZE** by manually providing all the required parameters.

**Comment by ttezel** [comment]
this should be fixed by #442. @gryp17 if you still have issues after updating to twit v2.2.11 feel free to reopen this!
