### ISSUE TITLE
destroy tweet is not working

### ISSUE THREAD

**Issue by pashalit85** [ttezel/twit#46]
I use this code 
T.post('statuses/destroy',{id: tweet_id}, function(err, reply) {
        console.log(err);
    })
and get 
{ statusCode: 404,
  data: '{"errors":[{"message":"Sorry, that page does not exist","code":34}]}',
  twitterReply: '{"errors":[{"message":"Sorry, that page does not exist","code":34}]}' }

**Comment by gangwarin98** [comment]
In the twit repository documentation you have written following :

//
//  destroy a tweet with id '343360866131001345'
//
T.post('statuses/destroy/:id', { id: '343360866131001345' }, function (err, data, response) {
  console.log(data)
})

Is it wrong?

**Comment by MatheusAvellar** [comment]
It's not wrong! From my testing, all of the following work:

```js
T.post("statuses/destroy", { id: id_str }, … );
T.post("statuses/destroy/:id", { id: id_str }, … );
T.post("statuses/destroy/" + id_str, … );
```
(where `id_str` is, of course, the ID string of the tweet you'd like to delete)

I'd also like to emphasize that, even though `T.delete()` exists, it is **unrelated to deleting a tweet**. I've spent way too long getting "400 BAD REQUEST" trying to delete a tweet using `T.delete`. That method refers only to the HTTP method "DELETE" (which [might actually be deprecated](https://github.com/abraham/twitteroauth/issues/444)), and not to the action of deleting a tweet. You should indeed use `T.post()` with the `statuses/destroy` url.
