### ISSUE TITLE
How can I get Tweets from the user logged?

### ISSUE THREAD

**Issue by tgmarinho** [ttezel/twit#495]
I created an APP on Twitter.
But I only getting my tweets, how can I get tweets from the logged user?

When the user make your signup,  I get and store your access token and acessTokenSecret, where I should put this information for getting your tweets?

```
const T = new Twit({
  consumer_key: Meteor.settings.twitterIntegration.CONSUMER_KEY,
  consumer_secret: Meteor.settings.twitterIntegration.CONSUMER_SECRET,
  access_token: Meteor.settings.twitterIntegration.ACCESS_TOKEN,
  access_token_secret: Meteor.settings.twitterIntegration.ACCESS_TOKEN_SECRET,
  timeout_ms: 60 * 1000, // optional HTTP request timeout to apply to all requests.
  strictSSL: false, // optional - requires SSL certificates to be valid.
});

// get new tweets from  timeline of logged user
export const getTweetsByHomeTimeline = () =>
  new Promise((resolve, reject) => {
    // TODO we should create a constant that store all endpoints
    T.get('statuses/home_timeline', {}, (error, data) => {
      if (error) reject(error);
      else resolve(data);
    });
  });
```

**Comment by marktani** [comment]
Use the endpoint `statuses/user_timeline` instead of `statuses/home_timeline`, the latter is only for  the authenticated user. See https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline

**Comment by tgmarinho** [comment]
Both require authentication. But now, I know how to get tweets from logger user! =)

I need to get the access_token and access_token_secreat from the user and pass to the parameter of instance new Twit.

Thanks! And closing it!
