### ISSUE TITLE
Direct Messages

### ISSUE THREAD

**Issue by jawadcode** [ttezel/twit#499]
How on earth do you send a direct message using the api because there is no documentation that I can find on it apart from outdated code that doesn't work?

**Comment by maziyarpanahi** [comment]
If this test fails, either Twitter has changed it’s APIs which I’m not aware of it or this library is outdated as you can see:
https://github.com/ttezel/twit/blob/642e62caaa8dc58e0e4697c63cb7243c1228c215/tests/rest.js#L275
You should use a library that is in active development with support for new APIs

**Comment by jawadcode** [comment]
@maziyarpanahi Does this send a direct message or check for them?

**Comment by maziyarpanahi** [comment]
Not sure, I’ve never used this API. You need to learn how to use Twitter APIs, this library is just a wrapper around those.
https://developer.twitter.com/en/docs/direct-messages/api-features
