### ISSUE TITLE
error code 324 when attempting to upload mp4 

### ISSUE THREAD

**Issue by JamesBotterill** [ttezel/twit#503]
I'm trying to upload an  6s (125kb) mp4 and I'm getting a Not Valid Video response back from twitter, 

I can't figure out why, I'm following the example in the readme and not sure what's happening

**Comment by JamesBotterill** [comment]
When using a gif generate from the video it works fine

**Comment by TheCynster** [comment]
I would like to look into this

**Comment by dalisalvador** [comment]
I'm having the same issue.... impossible to upload a .mp4 video :(

**Comment by alancoote** [comment]
This is due to postMediaChunked not using the upload STATUS command and testing for 'success'  before returning.

I raised a more detailed explanation in issue 517 - hopefully, it will get fixed.

**Comment by JamesBotterill** [comment]
For those who are still struggling with posting video I recommend using this repro instead 

https://github.com/bcomnes/twitter-video

It uses Twit for posting but has it's own video upload method.
