### ISSUE TITLE
No support for Application-only Authentication

### ISSUE THREAD

**Issue by vimota** [ttezel/twit#52]
I want to be able to use Application-only Auth for things like 'users/show' which require OAuth2. I haven't seen a way to do this with Twit as it is, is that right?

https://dev.twitter.com/docs/auth/application-only-auth

**Comment by mlodzianck** [comment]
Hey guys, i've just created PR with this feature implemented.
You can try it before merge by cloning my fork of twit. Any feedback highly appreciated.

**Comment by ttezel** [comment]
This was fixed in twit v2.0. Try it out and let me know if you have issues!
