### ISSUE TITLE
How to get tweets from stream dynamically

### ISSUE THREAD

**Issue by guischroeder** [ttezel/twit#523]
How can I restart the stream after I change the track outside the stream?

There's a stream.destroy() or something? I can't find something like that.
I want to destroy the stream and start my stream function again after get new hashtags from mongodb where i'm storing them after client input.

const stream = track => {
  const twitterStream = client.stream('statuses/filter', { track });
  
  twitterStream.on('tweet', tweet => {
     console.log(track)
  });
};

**Comment by Wazzabeee** [comment]
"stream.stop()
Call this function on the stream to stop streaming (closes the connection with Twitter)."

You can find find this here : https://github.com/ttezel/twit
In the section "Using the streaming API"

I hope it helps

**Comment by guischroeder** [comment]
But i just can call stream.stop() inside stream.on listener, i do not have access to do that outside the listener. 

So if i do inside the listener, it do not know when my track changes when i get a new one :(

**Comment by guischroeder** [comment]
> "stream.stop()
> Call this function on the stream to stop streaming (closes the connection with Twitter)."
> 
> You can find find this here : https://github.com/ttezel/twit
> In the section "Using the streaming API"
> 
> I hope it helps

But i just can call stream.stop() inside stream.on listener, i do not have access to do that outside the listener.

So if i do inside the listener, it do not know when my track changes when i get a new one :(
