### ISSUE TITLE
Access-Control-Allow-Origin problem

### ISSUE THREAD

**Issue by alperenarc** [ttezel/twit#526]
I try to post for destroy friendship but I had a problem.

`Access to fetch at 'https://api.twitter.com/1.1/friendships/destroy.json?user_id=%201464719845' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.` 

How can I fix that problem ?

**Comment by Kedar-K** [comment]
Hey, @alperenarc did you find any solution for this? I am facing the same issue

**Comment by alperenarc** [comment]
@Kedar-K You can add this line on package.json file "proxy": "https://api.twitter.com" or "proxy": "http://localhost:3000".
