### ISSUE TITLE
Reply to a tweet is possible?

### ISSUE THREAD

**Issue by johan-perso** [ttezel/twit#547]
Twit is not maintained, so I think reply to a tweet is impossible due to the change of the Twitter API… Is this just or no ?

**Comment by prphawk** [comment]
You can reply to any tweet as long as you have its id. Here's an exemple:
`
Bot.post('statuses/update', 
{ status: string, in_reply_to_status_id: string | number}, 
(err, data: Twitter.Status, res) => { ... }
`
