### ISSUE TITLE
[Streaming Api] Cannot search by bounding box AND keyword.

### ISSUE THREAD

**Issue by framerate** [ttezel/twit#57]
If I had "track" to my stream that is currently returning only San Francisco tweets, it starts returning me tons of tweets without geo-data.

Maybe this is intentional, but it's not in the documentation, which implies you can do "track" and "language" filters... so I'm led to believe I should be able to do "track" and "locations" right?

Thanks in advance!

**Comment by ttezel** [comment]
Thanks for the explanation @kai-koch ! Closing this.

**Comment by framerate** [comment]
Thanks guys!
