### ISSUE TITLE
Bad type checks

### ISSUE THREAD

**Issue by benjreinhart** [ttezel/twit#63]
Was perusing your code and noticed a couple of potential bugs. Just giving a friendly heads up that there a couple of type checks that won't work the way one would expect in JavaScript [here](https://github.com/ttezel/twit/blob/master/lib/auth.js#L20-L21) and [here](https://github.com/ttezel/twit/blob/master/lib/twitter.js#L94).

```
> typeof null
"object"
```

**Comment by ttezel** [comment]
Closing this as it no longer applies to the current code
