### ISSUE TITLE
How do you post on behalf of user?

### ISSUE THREAD

**Issue by tybenz** [ttezel/twit#68]
I'm not seeing anything glaringly obvious in the README on how to post a status on behalf of another user. According to twitter there has to be a 'Sign in with Twitter' feature to achieve this.

Please help! Thanks in advance!

**Comment by kafechew** [comment]
@ttezel : Mind to explain more? Or can you point me to the right place to read more about this? 

After an user login to my app with twitter account, we will have their accessToken & accessTokenSecret near the db.users under twitter. But there are no consumer key and consumer secret. 

Do you mean, with that accessToken & accessTokenSecret only of the user, the user can post "Hello world" without leaving the app?

The logic like ...

var thisUser = db.users.findOne().twitter;

var T = new Twit({
    access_token:         thisUser.accessToken, 
    access_token_secret:  thisUser.accessTokenSecret
});

T.post('statuses/update', { status: 'hello world!' }, function(err, data, response) {
  console.log(data)
})

Thanks!
