### ISSUE TITLE
Stream - delete event not fired

### ISSUE THREAD

**Issue by emelc** [ttezel/twit#76]
Hi,

It seems like the "delete" event isn't fired on an open stream.

If I open a stream:

var stream = T.stream('statuses/filter', { track: ['bla'] });

Add a tweet event:

stream.on('tweet', function (tweet) 
{ 
 console.log("tweet:" + tweet);
});

Add a delete event:

stream.on('delete', function (msg) {
  console.log("delete:" + msg);
});

... 'delete' doesn't run after a tweet that has previously tracked in the 'tweet' event is deleted from Twitter - issue or have I configured it incorrectly?

Thanks!

**Comment by kblcuk** [comment]
A year later, situation seems to be more-or-less the same:
https://twittercommunity.com/t/did-twitter-stop-sending-delete-notifications-in-the-streaming-api/41313/4
https://twittercommunity.com/t/keep-the-result-of-a-filtered-stream-in-sync-with-twitter-tos/37371

**Comment by ttezel** [comment]
Closing this as it's not a twit issue :)
