### ISSUE TITLE
rtd2.js Example 404 Searching For github.com/ Tweets

### ISSUE THREAD

**Issue by DatapawWolf** [ttezel/twit#86]
So I narrowed this down based on where the bot fails to run the command line paste I've inserted in the code:

```
        var params =
        {
            q: 'github.com/'
            , since: datestring()
            , result_type: 'mixed'
        };
        bot.twit.get('search', params, function (err, reply)
        {
            if(err) return handleError(err);
            
            console.log('\nAttempting tweet...');
            [...]
```
This log is never reached, and thus I get the idea that it fails to reach the search URL. I haven't edited the code any further than the original example, and so I'm guessing since this example has been updated/created, Twitter's API has been updated, rendering the code unusable in its current state. @ttezel

**Comment by ttezel** [comment]
This has been fixed! `npm update twit` to get the latest version. Thanks :)
