### ISSUE TITLE
Direct messages stream

### ISSUE THREAD

**Issue by dsalcedo** [ttezel/twit#87]
Any example for direct messages stream ?
or thats ok??
var stream = T.stream('direct_message');
stream.on('direct_message', function (msg) {
  console.log(msg)
})

**Comment by Brisingeros** [comment]
Hi, and sorry if my explanation is not very accurate. This is my code:

/////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////
var stream = T.stream('user');

stream.on('direct_message', createTweet);//////////////////////

//Lo que hace el bot

var sendPez = "pezpez";

function createTweet(eventMsg){ //////////////////////
	console.log("Working");

	var funct = true;
	var txt = eventMsg.direct_message.text;

	for(var i = 0; i <6 && funct; i++){
		funct = txt[i] == sendPez[i];
	}

	if(funct){
		var tw = "🐟🐟 ";

		for(var j = 7; j < txt.length; j++){
			tw = tw + txt[j];
		}

		console.log("Message is a order");
		tweetIt(tw);
	} else {
		console.log("It'a a message");
	}
};
/////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////////////////////////////////////////


My problem here is that stream doesn't detect any DMs. I'm a begginer, so it's possibly my fault, but I don't get where is the error.

Thanks in advance!!

**Comment by GarkGarcia** [comment]
I'm having the same problem here. Maybe it has something to do with the deprecation of `GET direct_messages`?
