### ISSUE TITLE
provide twitter.com certificate pinning

### ISSUE THREAD

**Issue by damianb** [ttezel/twit#88]
As on tin. Should provide a way to pin to a specific cert fingerprint - and have the default be the current twitter https cert.

**Comment by ttezel** [comment]
This is now supported. 

You may specify an array of trusted certificate fingerprints if you want to only trust a specific set of certificates. When an HTTP response is received, it is verified that the certificate was signed, and the peer certificate's fingerprint must be one of the values you specified. By default, the node.js trusted "root" CAs will be used.

eg.
```js
var twit = new Twit({
  consumer_key:         '...',
  consumer_secret:      '...',
  access_token:         '...',
  access_token_secret:  '...',
  trusted_cert_fingerprints: [
    '66:EA:47:62:D9:B1:4F:1A:AE:89:5F:68:BA:6B:8E:BB:F8:1D:BF:8E',
  ]
})
```

Run `npm update twit` to get it, and try it out! Thanks :)
