### ISSUE TITLE
Streaming API silently not working

### ISSUE THREAD

**Issue by nicola** [ttezel/twit#9]
Hello there, (yesterday it worked, but I  tried today and it didnt, I didnt change anything in the code),

here is my code:

var Twit = require('twit');
var T = new Twit({
    consumer_key:         'vroFy2FvOR8En7saib1A4Q'
    , consumer_secret:      '**_'
    , access_token:         '10818002-_'
    , access_token_secret:  '*'
});

var stream = T.stream('statuses/sample');
stream.on('tweet', function (tweet) {
  console.log(tweet); 
});
stream.on('error', function (tweet) {
  console.log(tweet); 
});

stream.on('limitation', function (tweet) {
  console.log(tweet); 
});

if I do node twit.js I get nothing and the process ends, any hints?

**Comment by KumarAbhirup** [comment]
Hey, as you said, we can't open many streams to the Twitter API and Twit closes the streamer currently running. None of my streamers are working or some do work for some time. This must be a problem that you illustrated. Is there a way to open more than 2 Streams in one js file?

**Comment by maziyarpanahi** [comment]
@KumarAbhirup there is no problem with having multiple streams in the same file or multiple files as long as all these streams have their own Twitter Application! Twitter won't allow connecting to one application multiple times and it will close it. 
Create multiple applications, use the credentials for each stream, and open them anywhere you like :)

**Comment by kumarabhirup** [comment]
Hey, there were two streams running. I completely shut down one. Why is second not working? any idea?

**Comment by kai-koch** [comment]
If you are running the streams in one file, the streams use most likely the same IP.
My guess is twitter does not allow 2 streams from the same IP-Adress even if they have a different Auth-Token each.

You would need a second IP Adress, even if it is just a virtual server on the same machine with a different IP. Twitter is very strict when it comes to give stuff away freely.
Dig through the the TOS of Twitter, if you can not set up a 2nd IP, to see if they allow multiple-connections from one IP-adress.
