### ISSUE TITLE
Refresh the track list of a stream

### ISSUE THREAD

**Issue by Art2B** [ttezel/twit#90]
How can I refreh a stream params to track more hashtag without relaunch my server ?
I have a database wich provides me the track list, and when a new hashtag to track is iserted, how can I refresh the stream track list ?

**Comment by allenfuller** [comment]
Sorry to dig up an old thread, but how would you loop this workflow?

For instance, stream1 runs for a few hours, then you switch to stream2. How about a few hours later when you need stream3, etc?

I may generate a random stream name, then store it in a variable, but maybe there's a better way?

And thank you for this great package! Looking at the code a lot of thought went into both the functionality and format.

**Comment by dsalcedo** [comment]
See https://github.com/SpiderStrategies/node-tweet-stream
```javascript
var Twitter = require('node-tweet-stream')
  , t = new Twitter({
    consumer_key: '',
    consumer_secret: '',
    token: '',
    token_secret: ''
  })

t.on('tweet', function (tweet) {
  console.log('tweet received', tweet)
})

t.on('error', function (err) {
  console.log('Oh no')
})

t.track('nodejs')
t.track('pizza')

// 5 minutes later
t.track('tacos')

// 10 minutes later
t.untrack('pizza')
```
