### ISSUE TITLE
Detect network errors?

### ISSUE THREAD

**Issue by chaodoze** [ttezel/twit#91]
How can I get notified when a stream has encountered a network error? e.g. when the network is severed?

I turned off my wifi on the node server but don't get notified with any of the following:
stream.on 'disconnect'
stream.on 'reconnect'
stream.on 'close'
stream.on 'error'

Thanks for a great library!

**Comment by ttezel** [comment]
In Twit v2.0, we perform exponential backoff if you lose network, and until you get network again, you will see of `connect` and `reconnect` events being fired until you get network again. Once you get network and a response is received from Twitter, the `connected` event will fire, and all the other usual events (`tweet` etc.) will be fired.
